### ISSUE TITLE
"Hello World" example from video doesn't work

### ISSUE THREAD

**Issue by elad** [johnwheeler/flask-ask#10]
This code:

```python
from flask import Flask
from flask.ext.ask import Ask, statement

app = Flask(__name__)
ask = Ask(app)

@ask.intent("HelloIntent")
def hello():
    return statement("hello from flask ask")

if __name__ == '__main__':
    app.run(debug=True)
```

Gives the following error:

```shell
$ python hello.py 
Traceback (most recent call last):
  File "hello.py", line 5, in <module>
    ask = Ask(app)
  File "/Library/Python/2.7/site-packages/flask_ask/core.py", line 39, in __init__
    self.init_app(app)
  File "/Library/Python/2.7/site-packages/flask_ask/core.py", line 43, in init_app
    raise TypeError("route is a required argument when app is not None")
TypeError: route is a required argument when app is not None
$ 
```

The fix is to add an explicit route, but I guess there should be a default set to `/_ask`?

Next, even if I add an explicit route, it errors with `400 Bad Request`. I see the incoming request in both the `ngrok` and `flask-ask` terminals, but **only** the fact that there is a request, **not** the actual request data:

Ngrok:

```
POST /_ask                     400 BAD REQUEST  
```

Flask-ask:

```
127.0.0.1 - - [10/Jun/2016 15:25:36] "POST /_ask HTTP/1.1" 400 -
```

What am I doing wrong?

**Comment by elad** [comment]
Turns out you really need to say "Alexa" first. :)

**Comment by johnwheeler** [comment]
Hi - Sorry elad - The constructor changed since that video was posted. I am working on new videos. Please keep an eye out at https://www.youtube.com/channel/UCZerPihWXzr6jV-rYK7KmIg

**Comment by bgrayburn** [comment]
@elad what do you mean you have to say alexa first? where's that? utterances?

**Comment by elad** [comment]
I don't have an Echo, so this was my first time playing with it via the simulator, and I missed on the fact that you need to say "Alexa" before everything else, as in "Alexa, tell foo bar." There is an exception though which is if you open a session ("Alexa, open foo") you can then proceed without saying "Alexa" first.

**Comment by johnwheeler** [comment]
reopening for the time being to make solution more visible until i change the video.

**Comment by bgrayburn** [comment]
@johnwheeler thank you! and thanks for this library!

**Comment by johnwheeler** [comment]
Video on readme updated
