### ISSUE TITLE
Amazon music is not supported for this device

### ISSUE THREAD

**Issue by Christina96** [johnwheeler/flask-ask#102]
I run the example without making any changes and I take this error. What should I do;

**Comment by johnwheeler** [comment]
Which example? This doesn't sound like it could be a Flask-Ask error.

**Comment by Christina96** [comment]
Yes I know but what can I do? (Example simple_demo)

Στις 21 Φεβ 2017 5:13 μ.μ., ο χρήστης "John Wheeler" <
notifications@github.com> έγραψε:

**Comment by johnwheeler** [comment]
Please post this question on StackOverflow. This issue tracker is for Flask-Ask issues specifically.
