### ISSUE TITLE
AMAZON.Date handling

### ISSUE THREAD

**Issue by grant-musick** [johnwheeler/flask-ask#104]
Mostly just a question about future intent. The conversion of AMAZON.Date "types" to Python datetime types loses information. In particular the following ones do not logically convert down to a single date:

“this week”: 2015-W48
“next week”: 2015-W49
“this weekend”: 2015-W48-WE
“this month”: 2015-11
“next year”: 2016
“this decade”: 201X
“next winter”: 2017-WI

Are the plans in the works to address this? I ask because I would rather use the framework approved solution. Otherwise I will make up my own version and, if it looks reasonable, submit it back for review.

**Comment by johnwheeler** [comment]
Hmmm.  I thought I captured these scenarios. Are you sure they're not
working?

**Comment by grant-musick** [comment]
The conversion works but the information lost is the duration. For example, if I ask Alexa "What is happening next weekend?" I get back a raw AMAZON.Date of "2017-W10-WE". And if I ask it "What is happening this Sunday?" I get back a raw AMAZON.Date of "2017-03-05".

But the first construct, implies multiple days (at least Saturday and Sunday and possibly part of Friday). So a corresponding date construct should capture this. It is either a start date and an end date or a start date and a duration. Technically you could argue that a day is also a start date and a duration but that is already captured in the data type.

I pulled out the relevant part of the convert code into a little script that illustrates the problem. You can see that "this weekend" and "Sunday" are equivalent after conversion and data about the original intent is lost.

`from __future__ import division, absolute_import, print_function, unicode_literals
import re
from datetime import datetime


_DATE_PATTERNS = {
    # "today", "tomorrow", "november twenty-fifth": 2015-11-25
    '^\d{4}-\d{2}-\d{2}$': '%Y-%m-%d',
    # "this week", "next week": 2015-W48
    '^\d{4}-W\d{2}$': '%Y-W%U-%w',
    # "this weekend": 2015-W48-WE
    '^\d{4}-W\d{2}-WE$': '%Y-W%U-WE-%w',
    # "this month": 2015-11
    '^\d{4}-\d{2}$': '%Y-%m',
    # "next year": 2016
    '^\d{4}$': '%Y',
}

SINGLE_DAY_PATTERN = '^\d{4}-\d{2}-\d{2}$'
YEAR_MONTH_PATTERN = '^\d{4}-W\d{2}$'
YEAR_PATTERN = '^\d{4}$'
WEEK_PATTERN = '^\d{4}-W\d{2}$'
WEEKEND_PATTERN = '^\d{4}-W\d{2}-WE$'
MONTH_PATTERN = '^\d{4}-\d{2}$'
YEAR_PATTERN = '^\d{4}$'
NOW_PATTERN = 'PRESENT_REF'


sample1 = "2017-W10-WE"
sample2 = "2017-03-05"
sample3 = "2017-03-04"

def to_date(amazon_date):
    # make so 'next decade' matches work against 'next year' regex
    amazon_date = re.sub('X$', '0', amazon_date)
    for re_pattern, format_pattern in list(_DATE_PATTERNS.items()):
        if re.match(re_pattern, amazon_date):
            if '%U' in format_pattern:
                # http://stackoverflow.com/a/17087427/1163855
                amazon_date += '-0'
            return datetime.strptime(amazon_date, format_pattern).date()
    return None


print(to_date(sample1))
print(to_date(sample2))
print(to_date(sample3))
print(to_date(sample1) == to_date(sample2)) # True
print(to_date(sample1) == to_date(sample3)) # False

`

**Comment by johnwheeler** [comment]
Ok, I see what you're saying. However, I think the `AMAZON.Duration`  is meant to cover durations and that AMAZON.Date is for a particular instant in time. The ISO 8601 seems to make the same distinction https://en.wikipedia.org/wiki/ISO_8601#Durations

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#duration

**Comment by grant-musick** [comment]
I have not played with their durations much yet and if they work per the ISO definition, then yes. However the Amazon documentation (and examples) indicates they are "based upon" but not implementing the standard.

That said even mapping a Python timedelta to an ISO duration b/c you can once again lose information if it includes the starting date. Bottom line is the mapping of AMAZON.DATE (and possibly AMAZON.DURATION) types to Python date/time/delta types is not a 1 to 1 match.

At the very least the convert function will eventually need to return a custom class (or two or three) that properly encapsulates the concept that DATE can return a datetime or a datetime and a timedelta or two datetime values to give a concept of the user intent e.g. "this weekend" (next Saturday and Sunday in the future) versus "this Sunday" (just a single day). 

I'll dig around and see if someone has already solved this problem. If not, I'll take a swing at it. Thanks for responding and thanks for making this framework. Saved me from working in Node.js and saved me from writing a bunch of boilerplate code.

**Comment by johnwheeler** [comment]
> At the very least the convert function will eventually need to return a custom class (or two or three) that properly encapsulates the concept that DATE can return a datetime or a datetime and a timedelta...

I appreciate you looking into this, but I think I'm inclined to disagree.

If Alexa asks, 

"What day would you like to book your trip?" 

and the user says,

"This weekend", "This decade", or "Next year"

I think it's reasonable for skills to default to the beginning instant of those. 

Similarly, if users said they wanted, "This Tuesday", we wouldn't want to give 

02-28-2017:00:00:00 to 02-28-2017:23:59:59 as a conversion.

I'm not saying that it couldn't be done that way, but it's easier from an API client perspective if you just dish out dates and then have Alexa ask for refinements like AMAZON.Time or AMAZON.Duration as follow up questions.

It could be argued that a date represents a particular instant in time in computer parlance (i.e. database record, Python datetime, java.util.Date) and that decades and weekends are not dates; therefore, a decade needs to be converted into a date if the data type is AMAZON.Date. A date should not necessarily be converted into a duration.

That's my line of reasoning. Let me know what you think.

**Comment by grant-musick** [comment]
The actual implementation is TBD, but the core problem still exists with the existing conversions. From an API perspective, converting AMAZON.DATE directly to python native types loses information. From a UI perspective, making the end user ask two questions when the Alexa API already provides enough information is not a good experience.

At a minimum, the interface of an AmazonDate type in Python will need to be able to signal to the programmer the start time and duration. For single days this could be as simple as yielding a date object (which automatically incapsulates duration). For times, it could be yielding a time object. But for weekends or weeks or seasons it needs to signal there is a start time and a duration b/c that is the minimum information required.

If you do not have that information, you are creating bugs (such as the current situation where you cannot differentiate between "this Sunday" and "this weekend") or extra work for the end user.

**Comment by johnwheeler** [comment]
Sorry, I disagree. Thanks again for your input.

**Comment by johnwheeler** [comment]
FYI Grant - I've been thinking about this for the last hour. It turns out the library I'm using interprets ISO patterns the same way I do and uses a different data structures for your interpretation. Please see the "Parsing dates"  vs. "Parsing intervals".

https://bitbucket.org/nielsenb/aniso8601/src

You might want to bring the issue up with the Alexa team to return these ISO structures. (See Parsing intervals). I would change the return type if they did.

**Comment by grant-musick** [comment]
Amazon is going to do what Amazon is going to do. We have to adapt to them. :)

Also, I figured someone out there had probably already solved (or taken a crack at) the representation issue. The issue is really that the Flask-Ask framework, as a bridge between the official Amazon REST API and Python is not properly converting the Amazon information into a correct representation. It can be fixed by making a new custom data type or by converting it into the something like what you referenced.

Anyway, I will take a crack at it b/c I need it. If it turns out to be interesting/useful, I will submit it back.
