### ISSUE TITLE
Can I trigger Alexa on a set time to play an audio file?

### ISSUE THREAD

**Issue by memoday** [johnwheeler/flask-ask#109]
First, thanks for the great Flask Ask. It's really a gem. 

I am creating an app that requests Rest API that has time values in it. My question is: is there a way to program Alexa using Flask Ask to automatically play an audio file at the called times from the rest api json call?

I would be grateful if you can guide me to the correct direction to get this done?

thanks,

**Comment by johnwheeler** [comment]
Hi memoday, The Alexa Skills Kit itself does not provide the ability to do that. You currently can't trigger time-based events and interactions have to be initiated by end users.
