### ISSUE TITLE
Problem installing via pip or python setup.py install on my AWS AMI

### ISSUE THREAD

**Issue by tpschmit** [johnwheeler/flask-ask#11]
Hi John

Great work you're doing here. THANK YOU!

I'm having a problem installing via pip or python setup.py install on my AWS AMI. See below for details. I downloaded the latest so I have an image of your repo. I think that should be enough to get me going?

Best,
Tom

<pre>
root@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/attic/flask-ask-master
# python setup.py install
running install
Checking .pth file support in /usr/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating Flask_Ask.egg-info
writing requirements to Flask_Ask.egg-info/requires.txt
writing Flask_Ask.egg-info/PKG-INFO
writing top-level names to Flask_Ask.egg-info/top_level.txt
writing dependency_links to Flask_Ask.egg-info/dependency_links.txt
writing manifest file 'Flask_Ask.egg-info/SOURCES.txt'
reading manifest file 'Flask_Ask.egg-info/SOURCES.txt'
writing manifest file 'Flask_Ask.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/flask_ask
copying flask_ask/__init__.py -> build/lib/flask_ask
copying flask_ask/convert.py -> build/lib/flask_ask
copying flask_ask/verifier.py -> build/lib/flask_ask
copying flask_ask/core.py -> build/lib/flask_ask
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/flask_ask
copying build/lib/flask_ask/__init__.py -> build/bdist.linux-x86_64/egg/flask_ask
copying build/lib/flask_ask/convert.py -> build/bdist.linux-x86_64/egg/flask_ask
copying build/lib/flask_ask/verifier.py -> build/bdist.linux-x86_64/egg/flask_ask
copying build/lib/flask_ask/core.py -> build/bdist.linux-x86_64/egg/flask_ask
byte-compiling build/bdist.linux-x86_64/egg/flask_ask/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/flask_ask/convert.py to convert.pyc
byte-compiling build/bdist.linux-x86_64/egg/flask_ask/verifier.py to verifier.pyc
byte-compiling build/bdist.linux-x86_64/egg/flask_ask/core.py to core.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Flask_Ask.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/Flask_Ask-0.7.5-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Flask_Ask-0.7.5-py2.7.egg
creating /usr/lib/python2.7/dist-packages/Flask_Ask-0.7.5-py2.7.egg
Extracting Flask_Ask-0.7.5-py2.7.egg to /usr/lib/python2.7/dist-packages
Adding Flask-Ask 0.7.5 to easy-install.pth file

Installed /usr/lib/python2.7/dist-packages/Flask_Ask-0.7.5-py2.7.egg
Processing dependencies for Flask-Ask==0.7.5
Searching for pyOpenSSL
Reading https://pypi.python.org/simple/pyOpenSSL/
Best match: pyOpenSSL 16.0.0
Downloading https://pypi.python.org/packages/77/f2/bccec75ca4280a9fa762a90a1b8b152a22eac5d9c726d7da1fcbfe0a20e6/pyOpenSSL-16.0.0.tar.gz#md5=9587d813dcf656e9f2760e41a3682dc3
Processing pyOpenSSL-16.0.0.tar.gz
Writing /tmp/easy_install-DTnPQ6/pyOpenSSL-16.0.0/setup.cfg
Running pyOpenSSL-16.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DTnPQ6/pyOpenSSL-16.0.0/egg-dist-tmp-JckXsj
warning: no previously-included files found matching 'leakcheck'
warning: no previously-included files matching '*.py' found under directory 'leakcheck'
warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching '.travis'
zip_safe flag not set; analyzing archive contents...
Moving pyOpenSSL-16.0.0-py2.7.egg to /usr/lib/python2.7/dist-packages
Adding pyOpenSSL 16.0.0 to easy-install.pth file

Installed /usr/lib/python2.7/dist-packages/pyOpenSSL-16.0.0-py2.7.egg
Searching for cryptography>=1.3
Reading https://pypi.python.org/simple/cryptography/
Best match: cryptography 1.4
Downloading https://pypi.python.org/packages/a9/5b/a383b3a778609fe8177bd51307b5ebeee369b353550675353f46cb99c6f0/cryptography-1.4.tar.gz#md5=a9763e3831cc7cdb402c028fac1ceb39
Processing cryptography-1.4.tar.gz
Writing /tmp/easy_install-Kmb5jt/cryptography-1.4/setup.cfg
Running cryptography-1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Kmb5jt/cryptography-1.4/egg-dist-tmp-wNL6P5
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
root@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/attic/flask-ask-master

$ cat /proc/version
Linux version 4.4.10-22.54.amzn1.x86_64 (mockbuild@gobi-build-60007) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue May 17 22:45:04 UTC 2016
ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
stepping        : 4
microcode       : 0x428
cpu MHz         : 2494.090
cache size      : 25600 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs            :
bogomips        : 4988.18
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ cat /proc/meminfo
MemTotal:        1019336 kB
MemFree:          190920 kB
MemAvailable:     764324 kB
Buffers:          165980 kB
Cached:           464092 kB
SwapCached:            0 kB
Active:           359380 kB
Inactive:         325224 kB
Active(anon):      54600 kB
Inactive(anon):      232 kB
Active(file):     304780 kB
Inactive(file):   324992 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         54524 kB
Mapped:            18656 kB
Shmem:               308 kB
Slab:             124916 kB
SReclaimable:     112512 kB
SUnreclaim:        12404 kB
KernelStack:        1680 kB
PageTables:         8228 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      509668 kB
Committed_AS:     172352 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       12288 kB
DirectMap2M:     1036288 kB
ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ df -ah
Filesystem      Size  Used Avail Use% Mounted on
proc               0     0     0    - /proc
sysfs              0     0     0    - /sys
/dev/xvda1       50G  2.0G   48G   4% /
devtmpfs        490M   60K  490M   1% /dev
devpts             0     0     0    - /dev/pts
tmpfs           498M     0  498M   0% /dev/shm
none               0     0     0    - /proc/sys/fs/binfmt_misc
ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ python -V
Python 2.7.10
ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ pip --version
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
ec2-user@ip-10-0-0-34:/var/www/cgi-bin/sandbox-tom/totalconnect2
$ gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</pre>

**Comment by johnwheeler** [comment]
Thanks for the kind words. I think you want: `sudo apt-get install libffi-dev`

**Comment by tpschmit** [comment]
After carefully ready that dump it clicked. You're close:
<pre>
sudo yum group install "Development Tools" and sudo yum install -y libffi libffi-devel
</pre>
