### ISSUE TITLE
alexa request url verification

### ISSUE THREAD

**Issue by DavidM42** [johnwheeler/flask-ask#111]
I have built an alexa skill using this framework and everything worked well but when I submitted it for certification to publish it one of the problems I got back was

>  Issues with skill endpoint validation The skill end-point is not accepting valid signed requests. Please make sure that your signature URL validation is correct. Please refer to our documentation on how to build your Alexa Skill as a web service and validate requests and signatures.

When I submitted it my config was ASK_VERIFY_REQUESTS = True which should be irrelevant because it's the default value and I did not have set  ASK_APPLICATION_ID (hosted on aws of different amazon account with zappa).
I now set the application ID and deleted the other setting and would like to know if this is a problem of flask ask or if I configured it wrong.

**Comment by johnwheeler** [comment]
Hi David,

I doubt it's a problem with Flask-Ask as there are numerous skills published with it.

I would just try again and you'll probably get another Alexa team member who reviews and passes it. From what I understand, the review process is atrocious and there's often no rhyme or reason to why skills get declined.

It's sort of a known problem on the Alexa team's end.

**Comment by DavidM42** [comment]
Thank you very much for your quick answer John :+1: .
I now set the application ID and changed the other points that were criticised of which only some were understandable and some did not got criticised last time.
So I hope my best for my 3rd time submitting this skill which hopefully won't take as long as the last two times with a whole week because I really want to get the free hoodie in Germany :D

**Comment by relighted** [comment]
David; you may still have a dormant error in one of your invocations, one which you maybe only can see occur when you publish the skill as developer for your own usage. The feedback you got is a standard blurp; the chance something is wrong with the signing is small. Check your cloudwatch logs details for any error after private publishing.

My own version of this was here ;) : https://forums.developer.amazon.com/questions/46194/feedback-the-skill-end-point-is-not-accepting-vali.html#answer-46446

**Comment by DavidM42** [comment]
I already test my skill development with my lambda production enviroment :D so it should not be a problem of a local dev setup but it really could be an error in one of my invocations or something like that. I had some not minor error and crash problems with the submitted version so general crashes f.e. if you invoke it without any intent could have been the problem.
