### ISSUE TITLE
No input, Session ended

### ISSUE THREAD

**Issue by Sean-Huntley** [johnwheeler/flask-ask#115]
Hey there,

Not sure If it's an error on my part but I'm writing a skill for Alexa using Flask-ask. My launch request works fine and then re-prompts. However, If there is absolutely no input for the user the session ends. I'm cool with that, however on this session-end I then get "There was a problem with the requested skill" vocalised by my echo. I'd rather a silent exit or a "Goodbye". 

Wondering how to resolve this.

Thanks.

**Comment by voutilad** [comment]
Hey @Sean-Huntley, coincidentally I was just dealing with this problem this week. Just opened PR #116  to address this. Feel free to manually do what it mentions for now (returning `"{}", 200`) or feel free to test my fork.

**Comment by johnwheeler** [comment]
also did a version bump so you should be able to 

`pip install -U flask-ask`

**Comment by Sean-Huntley** [comment]
Thanks!
