### ISSUE TITLE
Convert Alexa return value back to numeric word ( such as "5" into “five”)

### ISSUE THREAD

**Issue by shaolinkhoa** [johnwheeler/flask-ask#119]
Hi,
I tried to make alexa play music offline on my raspberry pi.
But there is a problem with some song have numeric word in it's name. 
Alexa always return automatically the digit (such as "5") instead of  numeric word even though I didn't use AMAZON.NUMBER.

 Example: song "Forever and one " always return " Forever and 1"
My **Intent Schema**:
```
{
  "intents": [
    {
      "slots": [
        {
          "name": "Song",
          "type": "LIST_OF_SONGS"
        }
      ],
      "intent": "ChooseSongs"
    },
    {
      "intent": "NoIntent"
    },
    {
      "intent": "AMAZON.HelpIntent"
    },
    {
      "intent": "AMAZON.StopIntent"
    },
    {
      "intent": "AMAZON.CancelIntent"
    }
  ]
}
```
my **Custom Slot Types**: LIST_OF_SONGS
```
Foreve and One  
When You Say Nothing At All
Knock Knock     
You don't have to call
Whatya Want From Me
Your Call 
```

my **Sample Utterances**:
```
ChooseSongs I want to hear {Song}
ChooseSongs I would like to hear {Song}
ChooseSongs I want to listen {Song}
ChooseSongs open {Song}
NoIntent no
```

Would you mind helping me ?

**Comment by johnwheeler** [comment]
Alexa always returns numbers in sentences as words. There is no way around that. You can however use something like this on the string

http://stackoverflow.com/questions/493174/is-there-a-way-to-convert-number-words-to-integers
