### ISSUE TITLE
not able install flask-ask using python

### ISSUE THREAD

**Issue by hitesh00025** [johnwheeler/flask-ask#121]
**This is on mac-OS Sierra:** 

kumarhit$ pip install flask-ask
Collecting flask-ask
  Using cached Flask-Ask-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d8/6krtbcq55m98klgcy9t32vzdn0tb39/T/pip-build-PzPjk9/flask-ask/setup.py", line 25, in <module>
        parse_requirements('requirements.txt', session=False)
      File "/Users/kumarhit/git/test/venv/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/Users/kumarhit/git/test/venv/lib/python2.7/site-packages/pip/download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by ByronBecker** [comment]
- Having the same issue

**Comment by johnwheeler** [comment]
@voutilad It appears we have some formatting issues with the last PR, and there's some invalid Python. I didn't do a very good job reviewing it. Can you take a look when you get a chance?

Everyone should pip install flask-ask==0.8.9 for the time being.

**Comment by johnwheeler** [comment]
This should be fixed for the time-being.

**Comment by voutilad** [comment]
Just noticed you're building source distributions that get distributed via PyPI. By default, setuptools doesn't grab the requirements.txt files when packaging.

I'll see what I can tweak, but I recommend building wheels: https://packaging.python.org/distributing/#wheels

**Comment by mahadevpy** [comment]
even flask 0.8.9 is not working:
I'm using python 3.4 (has pip)
I also tried using github and installing it, but it is of no avail
I HAVE A EMERGENCY, PLEASE REPLY FAST

HERE IS THE PREVIEW

![flaskask error](https://user-images.githubusercontent.com/32892515/31703869-3a4e9d5e-b3fc-11e7-8266-68b4d136ef3e.PNG)

**Comment by mahadevpy** [comment]
@johnwheeler 👎

**Comment by johnwheeler** [comment]
@mahadevpy the best i can do is https://github.com/btford/participating-in-open-source
