### ISSUE TITLE
Refactor to support latest changes distributed in PyPI

### ISSUE THREAD

**Issue by voutilad** [johnwheeler/flask-ask#122]
Need some slight tweaks to allow a release including the `pip`-friendly changes I tried to incorporate into what was `0.9`. (See Issue #121 and PR #120)

- [x]  add wheel support to setuptools-related files (e.g. setup.py, setup.cfg)
- [x]  make sure project works equally on Py2 and Py3 (required for universal wheels)

Ideally this refactor allows people that clone the project to simply run `pip install -r requirements-dev.txt` and they have everything required to run tests and hack on the code. Requirements files tend to do a better job making repeatable installations (see https://packaging.python.org/requirements/)

**Comment by voutilad** [comment]
I'm going to track this work in the `issue-122` branch.

**Comment by voutilad** [comment]
Still need to work out an issue with `python setup.py test` not working right, but the new `MANIFEST.in` file now bundles the requirements.txt files nicely. I'm refreshing my PyPI packaging memory via https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/ for those interested.

**Comment by voutilad** [comment]
@johnwheeler Just bumped the version number since master's `setup.py` was behind the released package on PyPI. Will you have a chance this week to try releasing to the staging PyPI so we can test a `pip install`?

**Comment by johnwheeler** [comment]
@voutilad Apologize for the delay Dave. I've uploaded the wheel to production and verified that it works -- 0.9.2 Thanks for this fantastic enhancement!
