### ISSUE TITLE
Support for getting user address?

### ISSUE THREAD

**Issue by RobRoseKnows** [johnwheeler/flask-ask#128]
Hi! I'm enjoying using Flask Ask but I was wondering whether or not it supports the [device address API](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api). I'm not seeing any documentation on it, but I might be missing something.

**Comment by johnwheeler** [comment]
Hi @RobRoseKnows,

Support for this was just added by @mc51 with this PR

https://github.com/johnwheeler/flask-ask/pull/127

I just pushed 0.9.3 to pypi, which incorporates this. Let us know how it goes.

**Comment by mc51** [comment]
Hi @RobRoseKnows. Take a look at the following blog post for a detailed description on using the address API with flask-ask: https://data-dive.com/alexa-get-device-location-from-custom-skill

Basically, you need to get the deviceId and consentToken from the user request. This can be done in flask-ask by retrieving the following elements:
context.System.device.deviceId
context.System.user.permissions.consentToken

In addition, the PR @johnwheeler  suggested can be used if the request does not provide a consentToken. This means, the user has not given your skill permission to access his address. Hence, you can ask for it with the consent_card. 

Neither the context object nor the consent_card is documented yet. I might give it a shot, if I find some time.
