### ISSUE TITLE
flask-ask_Zappa (Alexa skill) internal server error

### ISSUE THREAD

**Issue by Telecast101** [johnwheeler/flask-ask#135]
Zappa returns "Internal server error" after setting up an Alexa skill (works with ngrok)

## Context
I tried to load up an Alexa skill to a server by using Zappa and flask-ask. The Alexa skill works with ngrok. After installing Zappa by using this [guide](https://developer.amazon.com/de/blogs/post/8e8ad73a-99e9-4c0f-a7b3-60f92287b0bf/new-alexa-tutorial-deploy-flask-ask-skills-to-aws-lambda-with-zappa) from John Wheeler, everything works but if I enter the deploy-link to the browser it says "{"message": "Internal server error"}".

**Comment by voutilad** [comment]
Can you capture and provide a traceback from the AWS Lambda logs?

**Comment by johnwheeler** [comment]
@voutilad do you have a pypi login? I'd like to give you release access, which you can use as much or little as u desire (no expectations whatsoever on this end).

**Comment by voutilad** [comment]
@johnwheeler  Sure, it's `voutilad`

**Comment by johnwheeler** [comment]
Thanks Dave - I added you as a maintainer so you can push releases as you see fit.

**Comment by Telecast101** [comment]
@voutilad thank you for your quick response. Sorry I am quite a beginner in this area and this is my first project. I thought it is only possible to see the AWS Lambda logs by using an AWS Lambda blueprint but not by using Zappa with Lambda. Do you know where I can find it?
When testing the App with Alexa, I get this Error: "There was an error calling the remote endpoint, which returned HTTP 502 : Bad Gateway". 
I noticed that I used Python 3.6 instead of 2.7, could this be the issue?
Thank you for your help!, also to @johnwheeler for providing flask-ask. Hope I will get it run soon!

**Comment by Telecast101** [comment]
Finally I got the AWS Lambda [logs](https://www.dropbox.com/s/pkw54rpbdsecb52/flask-ask_Zappa_Alexa.txt?dl=0) but is there maybe another way to release the Alexa skill in Python without using Zappa? Does it work with a ngrok solution somehow?
