### ISSUE TITLE
flask-ask for java

### ISSUE THREAD

**Issue by shaolinkhoa** [johnwheeler/flask-ask#136]
Hi,

Thank you for creating flask-ask for python.
Do you have flask-ask version for java web ? or any Alexa java web tool similar with flask-ask ?

thank you

**Comment by voutilad** [comment]
I don't know of any, but it is possible to build very similar functionality on top of things like [Spring](http://projects.spring.io/spring-framework/) or maybe [Spark](http://sparkjava.com). Both frameworks are pretty powerful, but I don't think they come close to being as simple to use as Flask with Python.

**Comment by shaolinkhoa** [comment]
hi @voutilad ,
Thank you for your information.

On the **Test phase** of amazon skill. I see the Service Simulator send a _Service Request_ to my web:
```
{
  "session": {
    "sessionId": "SessionId.6bcd3265",
    "application": {
      "applicationId": "653-8d1f-a7df05d3ead6"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account."
    },
    "new": false
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.7",
    "locale": "en-US",
    "timestamp": "2017-06-05T03:00:29Z",
    "intent": {
      "name": "ControlDeviceIntent",
      "slots": {
        "Status": {
          "name": "Status",
          "value": "turn on"
        },
        "Device": {
          "name": "Device",
          "value": "light"
        }
      }
    }
  },
  "version": "1.0"
}
```
So it mean the skill will send a json package to my website right ? 
Do you know where I can find all the key of the json package ?
I mean I don't need to program a web like flask-ask, I just want to know all the possibilities of json key package which is sent.

Would you mind helping me ?
thank you

**Comment by treethought** [comment]
@shaolinkhoa you should be able to find all the info you need [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#request-format)
