### ISSUE TITLE
Test cases for Sample Apps fail to run on Windows

### ISSUE THREAD

**Issue by voutilad** [johnwheeler/flask-ask#137]
@Christina96 reported that the `tests/test_samples.py` test cases fail to run on Windows as the child Python processes crash on start. It looks to be related to explicitly setting the environment properties on the call to `subprocess.Popen()`. 

On macOS (and I'd presume other Unixes and Linux), the child process properly inherits environment settings from the forking process.

The implementation on Windows seems to call a Win32 system call that creates a new process but without setting the environment, causing Python's initialization routines to freak out while configuring the internal random hashing routines returning:

```Fatal Python error: failed to get random numbers to initialize Python```

Need to extend the test setup logic to detect OS and properly spawn the child processes for testing the samples.

**Comment by Christina96** [comment]
I fixed the problem. For running correctly on Windows was needed to add two variables in env (subprocess.Popen ()).
```
self.env = {'PYTHONPATH': project_root,
            'ASK_VERIFY_REQUESTS': 'false',
            'SYSTEMROOT': os.getenv('SYSTEMROOT'),
            'PATH': os.getenv('PATH')}
```
