### ISSUE TITLE
zappa deploy - Internal 500 error

### ISSUE THREAD

**Issue by rschmidtz** [johnwheeler/flask-ask#145]
Hi, I followed this tutorial from @johnwheeler  : [video](https://www.youtube.com/watch?v=mjWV4R2P4ks) and I'm getting a 500 error. My Alexa skill works locally with ngrok

Output from AWS API Gateway

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 433, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n', '  File \"/tmp/pip-build-jW5QZX/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

Here is my zappa_settings.json

```
{
    "dev": {
        "app_function": "skill.app", 
        "profile_name": "default", 
        "s3_bucket": "zapa-XXXX"
    }
}
```

Any thoughts?

**Comment by rschmidtz** [comment]
## Fix it

setupstools problem, refer [link](https://github.com/pypa/setuptools/issues/937)

### Fix it with 

pip install packaging

**Comment by GeorgianaPetria** [comment]
I'm getting the same 500 error and `pip install packaging` didn't work for me. Any idea what else I can do?
