### ISSUE TITLE
Many playlists

### ISSUE THREAD

**Issue by MarkRatFelt** [johnwheeler/flask-ask#149]
Hi! 
I loved the playlist sample. I was just wondering if:
- there is a way to having more than one playlist 
- Listing the name of the playlist could be possible. (like "you can play playlist1, playlist2, etc..." ) 

I mean, to have something like that:
`playlists = [
    playlist1 = [...],
    playlist2 = [...]
]`

and a way "to get" the playlists listed by name.

**Comment by PostsDesert** [comment]
@MarkRatFelt What do you mean by having more than one playlist? Geemusic supports playing all of your playlists.

You meant by voice, right? An intent where you would say "ask geemusic what playlists do I have?" or "ask geemusic to list my playlists" would be able to be added.

**Comment by MarkRatFelt** [comment]
Hi!
Thanks for your answer!

What I mean is:

In the playlist example, you have just one playlist (this one:
 playlist = [
    # 'https://www.freesound.org/data/previews/367/367142_2188-lq.mp3',
    '
https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3',
    '
https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3
',
    'https://archive.org/download/plpl011/plpl011_05-johnny_ripper-rain.mp3
',
    'https://archive.org/download/piano_by_maxmsp/beats107.mp3',
    '
https://archive.org/download/petescott20160927/20160927%20RC300-58-115.1bpm.mp3
',
    'https://archive.org/download/PianoScale/PianoScale.mp3',
    # '
https://archive.org/download/FemaleVoiceSample/Female_VoiceTalent_demo.mp4',
    '
https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Risset%20Drum%201.mp3
',
    '
https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Submarine.mp3',
    # '
https://ia800203.us.archive.org/27/items/CarelessWhisper_435/CarelessWhisper.ogg
'
])

And then you can say, "play" and it begins to play the playlist. And you
say "next" and it goes next because the queue.

Well, I would like to have more than one playlist, I would say, a list of
playlists (queues). And then you say "play" and then Alexa answers you "you
can choose between x, y and z" and then you say "x" and there you're in a
queue and it works as normal.

Let's say, something like this:

playlist = [
playlist1 = [
# 'https://www.freesound.org/data/previews/367/367142_2188-lq.mp3',
'https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3',
'
https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3
',
    'https://archive.org/download/plpl011/plpl011_05-johnny_ripper-rain.mp3
',
'https://archive.org/download/piano_by_maxmsp/beats107.mp3'
],
playlist2 = [
'
https://archive.org/download/petescott20160927/20160927%20RC300-58-115.1bpm.mp3
',
       'https://archive.org/download/PianoScale/PianoScale.mp3',
       # '
https://archive.org/download/FemaleVoiceSample/Female_VoiceTalent_demo.mp4',
               '
https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Risset%20Drum%201.mp3
'
],
playlist3 = [
                '
https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Submarine.mp3',
                # '
https://ia800203.us.archive.org/27/items/CarelessWhisper_435/CarelessWhisper.ogg
'
]
])




2017-07-18 3:22 GMT+02:00 Griffith Baker <notifications@github.com>:

**Comment by MarkRatFelt** [comment]
I already got it. I just used a slot_list which names of playlists. So, the user can decide which playlist he wants to listen.
