### ISSUE TITLE
Feature request: Echo Show Directives

### ISSUE THREAD

**Issue by johnddias** [johnwheeler/flask-ask#159]
With Echo Show there are now two directives for rendering the display and adding a hint on the display.  I wanted to use this in my skill so I added these lines to the _Field class in models.py:

```
def display_render(self, title=None, backButton=None, token=None, background_image_url=None, text=None, hintText=None):
        directive = [
        {
            'type': 'Display.RenderTemplate',
            'template': {
                'type': 'BodyTemplate1',
                'backButton': 'HIDDEN',
                'backgroundImage': {
                    'sources': [
                        {'url': background_image_url}
                    ]
                },
                'title': title,
                'textContent': text
            }
        }
        ]

        if token is not None:
            directive['template']['token'] = token
        if backButton is not None:
            directive['template']['backButton'] = backButton
        if hintText is not None:
            hint = {
                'type':'Hint',
                'hint': {
                    'type':"PlainText",
                    'text': hintText
                }
            }
            directive.append(hint)

        self._response['directives'] = directive
        return self
```

I was able to get this working, but I'm reluctant to make a pull request since I'm really not that experienced.  Also, there's a total of 6 templates for the display.render directive, I only added the first one.  If I am using the correct approach, I would be happy to add the additional templates and make a pull request.

**Comment by voutilad** [comment]
Nice! Definitely create a pull request as it helps visualize the changes you're proposing. When you do so, you can also reference this issue by putting the string `#159` in the title or description of the PR. That way they end up nicely linked.

We'll then be able to provide feedback, comment, and/or merge your PR a lot easier.

**Comment by johnddias** [comment]
Thanks, done!  Headed out for some time off so won't be responding for a week.
