### ISSUE TITLE
Query Without Opening Skill Functionality

### ISSUE THREAD

**Issue by maxlamberti** [johnwheeler/flask-ask#162]
Hi,

I was wondering how (if it's possible) to handle user intents that don't require the formal opening of a skill through flask-ask. What I mean is this type of requests:

"Alexa, ask <skill_name> what <something> is.
For example, "Alexa, ask Stockify what the current price of Apple Stock is."
or, "Alexa, ask Fitness Tracker how far I've run today."

So these are questions a user may ask Alexa without explicitly launching the skill (ie. without "Alexa, start memory game"). 

Best, 

Max

**Comment by rtgoodwin** [comment]
That's the normal behavior for a lot of skills, if I'm understanding your question. 

For example, if you say "open MySkill" or "start MySkill" (and you don't have a session open or any kind of data persistence going on), you'll hit the LaunchRequest intent. Mine gives some helpful hints about what you can ask for/say. (As the voice design guidelines suggest.)

If you say "ask MySkill to do X" then it will route directly the intent for X based on your Utterances. I.e. you don't have to first say "start MySkill". The act of matching an Utterance and sending an Intent implicitly triggers the skill and gives it the right information for Flask-Ask to route it to your specific intent. 

If you're saying you don't want to say "ask MySkill" at the beginning, then you have to either have an open session (like being in the middle of your example game skill), or be one of the special integrations (like for smart home stuff) that can handle bare commands like "Alexa turn off living room lights". 

Does that help?

**Comment by maxlamberti** [comment]
Yep! I just mishandled something because I thought the launch function is always called, but as you said it maps straight to the intent!

Thanks for your response!
