### ISSUE TITLE
No module named _openssl (Python 2.7)

### ISSUE THREAD

**Issue by jlindsey1** [johnwheeler/flask-ask#167]
Hi,

I have been using flask-ask along with Zappa to create an Alexa skill, and all has been working without error. However, due to external circumstances, I can no longer use Zappa for deployment, and must do so manually by uploading a .zip file etc. ([Creating a deployment package.](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html))

I progressed through this fine, but when importing flask_ask, the try/catch error I receive is:

`No module named _openssl`

I've tried reinstalling flask_ask, cryptography, pyopenssl, all to no avail. All of this has been done within a virtual environment, and zipped within the site-packages folder. The hello-world code also runs if flask_ask is not imported.

Any help and advice would be much appreciated!

**Comment by scott------** [comment]
I have the same issue.

**Comment by johnwheeler** [comment]
You will not be able to deploy to Lambda without Zappa. Zappa provides a WSGI emulation layer that Flask requires in order to run

**Comment by jlindsey1** [comment]
Is there any way to work around that, however convoluted that may be? 

If not, thank you for the help!

**Comment by johnwheeler** [comment]
Unfortunately no, it's a pretty major architectural issue, and there's no way around. Zappa provides a ton of the code that underpins getting flask to work on lambda (not just flask-ask)
