### ISSUE TITLE
End of the playlist

### ISSUE THREAD

**Issue by MarkRatFelt** [johnwheeler/flask-ask#173]
Hi!
I'm having a problem. 

When the playlist is over, it should happen this code:

```
@ask.on_playback_finished()
def play_back_finished():
    _infodump('Finished Audio stream for track {}'.format(queue.current_position))
    if queue.up_next:
        queue.step()
        _infodump('stepped queue forward')
        dump_stream_info()
    else:
        return statement('You have reached the end of the playlist!')
```

If I print something there, it works, but the problem is, that Alexa never says "You have reached the end of the playlist" I also tried with "audio()" and it doesn't work. 

I toke a look in the logs and I get this: 

`"Finished Audio stream for track 4"` that's good. 
but then:
```[INFO]	2017-08-06T11:27:46.693Z	456e5441-7a9a-11e7-ba31-f976d693269e	54.240.197.10 - - [06/Aug/2017:11:27:46 +0000] "POST / HTTP/1.1" 400 0 "" "Apache-HttpClient/4.5.x (Java/1.8.0_131)" 0/37.624```
I think it happens because of the "audio()" or "statement()" 

Does anybody have an idea? I would like actually to use "question()"

**Comment by nealrs** [comment]
@MarkRatFelt You can't follow up an `audio()` with a `question` or `statement`. Alexa closes the session when you play longform audio via the audioplayer directives. Kind of a bummer 😑

**Comment by MarkRatFelt** [comment]
@nealrs Thanks for your answer! 

I just don't understand something. 

When you use the NextIntent, you've this code:
```
        speech = 'playing next queued song'
        next_stream = queue.step()
        _infodump('Stepped queue forward to {}'.format(next_stream))
        dump_stream_info()
        return audio(speech).play(next_stream)

```
And there Alexa says the speech,  but in `@ask.on_playback_nearly_finished()` you've this `return audio().enqueue(next_stream)` and I understand that you can't put a speech in `audio()` because Alexa still stream Audio. 

Do you know if there's a way that Alexa says something between to songs of the playlist, just the way she does in the NextIntent? 

e.G. a playlist with two songs, and when she's moving from the first to the second (without the user saying "next") she says something like "Now comes the next song". Do you know if that's possible ? 

I tried in @ask.on_playback_stopped() but it doesn't work.

**Comment by nealrs** [comment]
@MarkRatFelt Nope, I don't think Alexa supports that. Would be useful though.  ☹️
