### ISSUE TITLE
error when installing flask-ask in raspberry pi

### ISSUE THREAD

**Issue by shaoenliu** [johnwheeler/flask-ask#198]
when i want to install flask-ask in raspberry pi, these errors come out, anyone knows what is happening?
![2017-10-19-094310_1920x1080_scrot](https://user-images.githubusercontent.com/28526287/31771697-9aa14028-b4cc-11e7-80e0-813f1cee62b2.png)

**Comment by shaoenliu** [comment]
`Downloading/unpacking flask-ask
  Downloading Flask_Ask-0.9.7-py2.py3-none-any.whl
Downloading/unpacking PyYAML==3.12 (from flask-ask)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-OzH9Gj/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking pyOpenSSL==17.0.0 (from flask-ask)
  Downloading pyOpenSSL-17.0.0-py2.py3-none-any.whl (51kB): 51kB downloaded
Downloading/unpacking aniso8601==1.2.0 (from flask-ask)
  Downloading aniso8601-1.2.0.tar.gz (59kB): 59kB downloaded
  Running setup.py (path:/tmp/pip-build-OzH9Gj/aniso8601/setup.py) egg_info for package aniso8601
    
Downloading/unpacking Flask==0.12.1 (from flask-ask)
  Downloading Flask-0.12.1-py2.py3-none-any.whl (82kB): 82kB downloaded
Downloading/unpacking six==1.10.0 (from flask-ask)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking cryptography>=1.7 (from pyOpenSSL==17.0.0->flask-ask)
  Downloading cryptography-2.1.1.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-OzH9Gj/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-OzH9Gj/cryptography
Storing debug log for failure in /root/.pip/pip.log
`

**Comment by jamaalscarlett** [comment]
python_version < '3'

My first guess would be that you are trying to install using python 2.7

**Comment by shaoenliu** [comment]
actually it is, but anyway the problem has been solved, the problem is that the cryptography.py was not installed perfectly, and I download the needed files seperately and then works.
