### ISSUE TITLE
Add feature to disable request verification for testing the apps

### ISSUE THREAD

**Issue by sasinda** [johnwheeler/flask-ask#20]
Tried to stress test the application by mocking the json requests from Amazon echo. But it is not possible due to the request verification.
Add option to disable request verification for testing.
These steps throw errors if it is not signed by amazon.
cert_url = flask_request.headers['Signaturecertchainurl']
signature = flask_request.headers['Signature']

**Comment by johnwheeler** [comment]
Hi Sasinda - 

I've added this feature and pushed a new release to PyPi (0.7.6)

Please test it out and let me know. Here are the docs

https://alexatutorial.com/flask-ask/configuration.html

**Comment by sasinda** [comment]
Oh cool! thanks for doing it so quickly. Please disregard my pull request. I'll test and close soon.

Best,
Sasinda.

**Comment by johnwheeler** [comment]
Thanks for the nice PR - looks like we're on the same page implementation wise. I went ahead and closed it.

**Comment by sasinda** [comment]
Thanks. Can you put the  request header checking logic also under the "if verify:" check. That would ease up mock requests since we wan't need to fill in dummy headers.
        if verify:
            cert_url = flask_request.headers['Signaturecertchainurl']
            signature = flask_request.headers['Signature']

**Comment by johnwheeler** [comment]
Yikes! Sorry about that. It's cleaner too. Done and new version pushed up to PyPi (0.7.7)

**Comment by sasinda** [comment]
Thanks. Works perfect now!
