### ISSUE TITLE
Unable to use Amazon built-in MusicGroup Intents and slots

### ISSUE THREAD

**Issue by andocromn** [johnwheeler/flask-ask#203]
I am working on making an audio player skill with flask ask using the built-in MusicGroup Intents referenced here https://developer.amazon.com/docs/custom-skills/musicgroup-intents.html#musicgroup-slots

according to this documentation and my tests, the intent "AMAZON.SearchAction<object@MusicGroup>" has a slot named "object.name" which I am trying to bring into my function however I am unable to because if I include the dot in the function's parameter it results in a syntax error.  if I exclude the . and just use objectname it appears empty and returns "None" instead of the input.  I'll provide some excerpts of my code and the JSON

is there some way to capture this slot into a variable or is formatting of the built-in slot with the dot going to make it impossible? 

flask ask python code:
`@ask.intent("AMAZON.SearchAction<object@MusicGroup>")
def play_artist(objectname):
    speech_text = "I will play %s" % objectname
    return statement(speech_text)
`

json request:
` "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.******",
    "intent": {
      "name": "AMAZON.SearchAction<object@MusicGroup>",
      "slots": {
        "object.name": {
          "name": "object.name",
          "value": "black sabbath"
        }
      }
    },
 `

json response:
`{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "I will play None",
      "type": "PlainText"
    },
    "speechletResponse": {
      "outputSpeech": {
        "text": "I will play None"
      },
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}`

**Comment by foxy82** [comment]
Have you tried using mappings like this?

@ask.intent('WeatherIntent', mapping={'city': 'City'})
def weather(city):
    return statement('I predict great weather for {}'.format(city))

**Comment by andocromn** [comment]
thank you!
