### ISSUE TITLE
When submitting app to certification it is rejected

### ISSUE THREAD

**Issue by Toriniasty** [johnwheeler/flask-ask#207]
Hi,
When submitting Alexa Skill for certification it gets automatically rejected with following reason:
"The skill end-point is not accepting valid signed requests. Please check if your signature URL validation logic is correct. Please refer to our documentation on how to build your Alexa Skill as a web service and validate requests and signatures."

I'm not quite sure what's wrong. It's an HTTPS endpoint with wildcard certificate. Skill works perfectly fine on my Echo and in simulator.

Versions of flasks:
Flask==0.12.1
Flask-Ask==0.9.7

What can I do with following problems?

Cheers

**Comment by xandr2** [comment]
Did you solve the problem?

**Comment by Toriniasty** [comment]
Hey,
Yes - simple PEBKAC.

Cheers!
