### ISSUE TITLE
flask-ask returns null response on AWS Lambda but not locally with ngrok

### ISSUE THREAD

**Issue by josephquigley** [johnwheeler/flask-ask#23]
I've been tweaking things for hours and haven't found a way to get flask-ask to run on AWS lambda. The same request that works with ngrok locally returns a "null" response in the Lambda execution results. The only info that gets logged when I deploy with Zappa is the following:

`Zappa Event: {u'session': {u'new': True, u'sessionId': u'SessionId.[redacted]', u'user': {u'userId': u'amzn1.ask.account.[redacted]'}, u'application': {u'applicationId': u'amzn1
[DEBUG]	2016-09-06T04:44:50.804Z	[redacted]	Zappa Event: {u'session': {u'new': True, u'sessionId': u'SessionId.[redacted]', u'user': {u'userId': u'amzn1.ask.account.[redacted]
END RequestId: [redacted]`

I am running the [memory game example](https://developer.amazon.com/appsandservices/community/post/Tx14R0IYYGH3SKT/Flask-Ask-A-New-Python-Framework-for-Rapid-Alexa-Skills-Kit-Development), but have also used the flask-ask helloworld example without success.

Not sure if this is a bug, or just the result of a documentation omission on what is needed to get ask-flask to run on AWS Lambda (since the only info I can find says "use ngrok, it's easy to test with").

**Comment by johnwheeler** [comment]
you have to use zappa

**Comment by johnwheeler** [comment]
easiest deploy to lambda ever https://github.com/Miserlou/Zappa

**Comment by josephquigley** [comment]
Wow. Thanks for the fast reply! I am using Zappa.

**Comment by johnwheeler** [comment]
Sorry Joseph, I just saw you put that in your OP. are you using ARN or HTTPS endpoint. I've only tested it with HTTPS-based endpoint

**Comment by josephquigley** [comment]
Sorry, for the re-open. Replied to the github email and it never posted 😡

I am using ARN.

**Comment by johnwheeler** [comment]
Use HTTPS with the Cloud Endpoint gateway doled out by Zappa. Do not use ARN

**Comment by josephquigley** [comment]
Ah, that makes sense. Thanks!

**Comment by heitatta** [comment]
Same issue happened, and same reason.

I'd like to deploy my application as lambda (ARN) because it is a kind of ASK standard, and it's more secure than HTTPS end point. But there isn't any established way to do that and I have to write my own handler instantiating Flask app and feeding events to them....orz
