### ISSUE TITLE
Card images not working

### ISSUE THREAD

**Issue by jaredcasale** [johnwheeler/flask-ask#24]
The smallImageUrl and largeImageUrl attributes of the response object should be inside an image object rather than as part of the base card object. You can see the format required [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app):

`
{
  "version": "1.0",
  "response": {
    "outputSpeech": {"type":"PlainText","text":"Your Car-Fu car is on the way!"},
    "card": {
      "type": "Standard",
      "title": "Ordering a Car",
      "text": "Your ride is on the way to 123 Main Street!\nEstimated cost for this ride: $25",
      "image": {
        "smallImageUrl": "https://carfu.com/resources/card-images/race-car-small.png",
        "largeImageUrl": "https://carfu.com/resources/card-images/race-car-large.png"
      }
    }
  }
}
`

(apologies for the formatting, it looks much nicer on the Amazon Developer page).

On line 249 of core.py, the image URLs should be inserted into their own dictionary before being assigned to an 'image' key of the card dictionary (if they exist).

Awesome library by the way, thank you for building it!

**Comment by johnwheeler** [comment]
HI - If you PR I'll merge it fast. Otherwise I have to back burner this for a bit. can't take focus off current priority

**Comment by jaredcasale** [comment]
It's not high pri, I can work around easily. Thanks!

**Comment by johnwheeler** [comment]
thank you for reporting
