### ISSUE TITLE
Combind Efforts?

### ISSUE THREAD

**Issue by rocktavious** [johnwheeler/flask-ask#28]
Hey,

I recently learned about this project and i think its possibly we could have some combind efforts to make a set of libraries that make writing ASK integrations for all the web frameworks, that all use a similar set of API's but then also have the web framework specific packages that give you the tools to integrate with that web framework

Something like:

py-ask - base methods and classes that deal with the data and responses formats
django-ask - django specific integration that uses the core methods and classes from py-ask
flask-ask - flask specific ... etc

I wrote - https://github.com/rocktavious/django-alexa

I also reached out to - https://github.com/anjishnu/ask-alexa-pykit/issues/3

Let me know what you think.

**Comment by johnwheeler** [comment]
I think it's a good idea, but I've never really collaborated in that way and don't want to give up the  complete control I have with Flask-Ask. I'm willing to listen and watch where you take this idea though, rock.

**Comment by rocktavious** [comment]
Ok, i'll block out a repo that extracts out the parts i think could be shared between our repos and then give your a collaborators role on it so you can have control of it too.  Then its just a matter of modifying the base with additional needs, release a new package and each of our repo's to use that package and shared functionality.  If i don't get to it this weekend, probably sometime before Nov.

**Comment by RyanBalfanz** [comment]
@rocktavious Do you make a repo? I'd like to follow the progress.
