### ISSUE TITLE
async notifications from flask-ask

### ISSUE THREAD

**Issue by sameermahajan** [johnwheeler/flask-ask#29]
Hello,

When is alexa / flask-ask going to support async notifications from flask-ask to alexa? The use cases are sending alerts based on some events.

thanks,
Sameer

**Comment by johnwheeler** [comment]
Hi Sameer - I don't know if the Alexa Skills Kit supports that yet. Does it?

**Comment by sameermahajan** [comment]
not yet. but it is stated to be coming up this fall:

http://www.digitaltrends.com/home/amazon-alexa-push-notifications-fall-voice-activated/

which I suppose could be anytime now...

How can it be tracked to be made available in flask ask when it is
supported in ASK?

**Comment by johnwheeler** [comment]
It really hasn't been on my radar. I can't give an ETA on it since there's no concrete dates or documentation, but PRs are welcome when the time comes :)

**Comment by sameermahajan** [comment]
Thanks John. I would sure keep you posted if I hear anything regarding this!

**Comment by johnwheeler** [comment]
We can keep the issue open, but I don't know exactly when I can slot out time for it - Thanks Sameer

**Comment by johnwheeler** [comment]
Closing this down for now for housecleaning. If async functionality goes into the official ASK, feel free to reopen
