### ISSUE TITLE
docstrings and Sphinx autodoc

### ISSUE THREAD

**Issue by johnwheeler** [johnwheeler/flask-ask#3]

**Comment by mattgathu** [comment]
**Hello John**,

I am Python intermediate dev looking to make open source contributions and would be glad to help out on this issue. 
cheers

**Comment by johnwheeler** [comment]
Hi! Sure, I'd love some help. 

#. Please fork
#. Find some method you want to document in the codebase
#. Follow PEP doc guidelines https://www.python.org/dev/peps/pep-0257/ 
#. Create PR

Thanks!
John
