### ISSUE TITLE
Update for streaming audio feature of ASK SDK

### ISSUE THREAD

**Issue by SenseAmidMadness** [johnwheeler/flask-ask#30]
Is there a plan to implement audio file playback in the skill? https://github.com/alexa/skill-sample-nodejs-audio-player

**Comment by johnwheeler** [comment]
Hi SenseAmidMadness. There are plans, but one of these factors will play into it.

1. My own needs
1. Company sponsorship
1. Pull Request with code that fits in with the rest of the design of Flask-Ask

**Comment by johnwheeler** [comment]
This has been added by @treethought. Please see the audio sample.
