### ISSUE TITLE
Request' object has no attribute 'locale'

### ISSUE THREAD

**Issue by relighted** [johnwheeler/flask-ask#36]
Now that language (German vs English)  is an option in skill design it needs input to switch,    how can I use this dynamicaly in code? 
The input json has this as an attribute ( **"locale": "en-US",**) in the request ,  how can I use this in the intent calls ? 

`,
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.00000000000000000000000000",
    **"locale": "en-US",**
    "timestamp": "2016-11-04T20:37:27Z",
    "intent": {
      "name": "Intendname",
      "slots": {
        "blaat": {
          "name": "foo",
          "value": "bars"
        }
      }
    }
`

**Comment by relighted** [comment]
I found in the flask-ask documentation the relevant section on the session & requests. 
( http://flask-ask.readthedocs.io/en/latest/requests.html#request-session-and-version-context-locals ) 

This works for attributes like request.type. 
But for request.locale it returns an error. What am I doing wrong here?

`log.info("Request LOCALE: {}".format(request.locale))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_Request' object has no attribute 'locale'`

**Comment by treethought** [comment]
You should now be able to access it with request.locale.

**Comment by relighted** [comment]
I'll update and confirm,  thanks!  This will open up the German skill market for use with the library.

**Comment by relighted** [comment]
I've patched my local core.py manually, but this does not seem to resolve the issue. 

`  print("LOCALE: " + format(request.locale))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_Request' object has no attribute 'locale'`

**Comment by johnwheeler** [comment]
This should be fixed with @treethought's new request parsing logic.
