### ISSUE TITLE
Certification Verification Error

### ISSUE THREAD

**Issue by aayush26** [johnwheeler/flask-ask#37]
File "C:\Program Files\Anaconda2\lib\site-packages\flask_ask\verifier.py",  line 22, in load_certificate  
    raise VerificationError("Certificate verification failed")  
VerificationError: Certificate verification failed  

I am using ngrok to create https url. I am following the exact steps as per your [tutorial](https://developer.amazon.com/public/community/post/Tx14R0IYYGH3SKT/Flask-Ask-A-New-Python-Framework-for-Rapid-Alexa-Skills-Kit-Development).
Few weeks ago, my skill was running perfectly. But now its showing certification error.

**Comment by aayush26** [comment]
Solved using
`app.config['ASK_VERIFY_REQUESTS'] = False`

**Comment by relighted** [comment]
There was also an issue for a little moment on Alexa side where the cert was expired.  Perhaps this had to do with that.  (resolved now),  see alexa development forum)
