### ISSUE TITLE
User Linking

### ISSUE THREAD

**Issue by melchoir55** [johnwheeler/flask-ask#4]
The process amazon uses for linking users between alexa and a 3rd party system is fairly complex. It would be quite helpful if flask-ask had a built-in default (or an example) of serving the necessary endpoint that alexa wants in order to establish account linking.

**Comment by johnwheeler** [comment]
From what I understand, you just supply the LinkAccount card type and configure the endpoint during skill configuration. I'll investigate further and report back.

**Comment by melchoir55** [comment]
The docs talk about what looks like providing some endpoint which accepts Oauth2, and about redirecting the user to an amazon site while embedding your app-specific authentication token in the url. (the token you want alexa to pass in the future to identify the user). It isn't clear to me why Oauth2 is involved if the app is providing it's own non-Oauth token to Alexa for future use. I figured others might be as confused as me, and that an example in Flask-Ask (if not some supporting methods/classes) would probably help a lot of people since account linking is going to be a very common thing folks will want to do.

Great module by the way.

**Comment by johnwheeler** [comment]
Yep. I'm confused too. If it turns out I can bake some sort of guidance into the API constructs, I will. Otherwise, I think a sample piece or some instruction to make it easier to understand is a good idea.

**Comment by johnwheeler** [comment]
Backburnering

**Comment by rudf0rd** [comment]
Hey just leaving a note here in case someone else finds this like I did.

If you have everything configured properly in your Alexa skill, you will receive your OAuth2 access token in `session.user.accessToken`.  I use this attr to check and catch if I need to show the `link_account_card` within the flask ask portion.  That part looks:

```
def account_is_linked():
    if hasattr(session, 'user') and hasattr(session.user, 'accessToken'):
        return True
    else:
        return False
```

**Comment by johnwheeler** [comment]
Thank you - reopening issue

**Comment by heytimj** [comment]
Kind of in the same vein - is there a built in way to return the 'LinkAccount' card type?

**Comment by johnwheeler** [comment]
@heytimj it is undocumented but it's there

https://github.com/johnwheeler/flask-ask/blob/master/flask_ask/models.py#L82

**Comment by heytimj** [comment]
thanks for the lightening fast response, @johnwheeler. not to mention flask-ask as a whole :)

**Comment by cscanlin** [comment]
I'm going to be taking a stab at this.

I found this blog post which demonstrates how to accomplish this in Rails with a gem called doorkeeper: https://echobind.com/blog/alexa-custom-skills-with-account-linking/

It looks like Flask has a similar package called [Flask-OAuthlib](http://flask-oauthlib.readthedocs.io/en/latest/oauth2.html) that could be used for similar purposes.

Will report back once I've got something working, and hopefully I'll have some ideas on how to implement this into flask-ask.

**Comment by yjkimjunior** [comment]
@cscanlin bump. How's it going? I'd love to help out if possible!

**Comment by cscanlin** [comment]
Hey sorry for the delay, but I would love some help! Here's a link to the repo:
https://github.com/cscanlin/ask-auth

I've got two versions so far:

1. A basic example that uses the sessions `userId` to persist data between sessions (branch [`simple-demo`](https://github.com/cscanlin/ask-auth/tree/simple-demo)).

2. A more fleshed out version that uses OAuth to link the account to a user in a database ([`master`](https://github.com/cscanlin/ask-auth) branch)

The basic example is based on this bit of information buried in the account linking section:

  > Note that account linking is needed when the skill needs to connect with a system that requires authentication. If your custom skill just needs to keep track of a user to save attributes between sessions, you do not need to use account linking. Instead, you can use the `userId` provided in each request to identify the user. The `userId` for a given user is generated when the user enables your skill in the Alexa app. Every subsequent request from that user to your skill contains the same `userId` unless the user disables the skill.

I suspect that 95% of flask-ask users who think they need account linking, probably just need something more like this (most people who need OAuth are doing almost everything custom).

Both versions currently use the [PynamoDB](https://github.com/pynamodb/PynamoDB) wrapper around AWS DynamoDB NoSQL service, but that adds 5mb overhead to the zipfile for uploading to lambda. It wouldn't be too hard to write a small custom wrapper for `flask-ask`, but the bulk of the overhead may be in the `boto3` package (I haven't tested). If that's the case, I'm not sure it would ever make sense to include in `flask-ask` by default, but it could still be provided as an example or a companion library.

Using a NoSQL db is not a requirement either, but it is the suggested way for most of the basic alexa db use cases. It would relatively trivial to migrate to a RDBS and would probably be better for the next part too.

--------------------------------------------------------------------

The second version is still my final goal, and is based off of this example: https://github.com/lepture/example-oauth2-server/blob/master/app.py

The first part of the flow works, but I still haven't managed to successfully link yet.

The first problem is that the request to link access doesn't seem to include the alexa userId. My plan was to use the alexa userId as the primary key (or hash index w/e) for the user, so the user doesn't have to create a separate account, but I don't see how this would be possible. Right now I'm working around this by storing my userId in an environment variable, but this needs to be solved.

The other problem is that the alexa auth flow seems to work differently than the example. I'm struggling to figure out exactly how the example/library works, but the account linking fails when the alexa app tries to hit the `/oauth/token` endpoint and fails to return a token. The `code` that is set in the `redirect_uri` for `Grant` is provided when the request to `/oauth/token` (I have no idea how the library does it, it doesn't explicitly happen in the `authorize_handler`)

In any case, I can answer any other questions, and you'll probably have a better time just testing it yourself, but I need to post this comment now or I never will :P

**Comment by caseydm** [comment]
Has anybody used Login with Amazon and account linking similar to this tutorial: https://developer.amazon.com/blogs/post/Tx3CX1ETRZZ2NPC/Alexa-Account-Linking-5-Steps-to-Seamlessly-Link-Your-Alexa-Skill-with-Login-wit, with the sole purpose of obtaining the user's email address to look up other information? I'm considering using the link_account card and am wondering if it will work properly.

**Comment by voutilad** [comment]
@caseydm I believe it will all come down to the scope you request during the OAuth exchange. For "Login with Amazon" it looks like you need at least the [profile scope](https://developer.amazon.com/public/apis/engage/login-with-amazon/docs/customer_profile.html). A similar thing applies to any other OAuth providers (Twitter, Google, Facebook, etc.). 

@cscanlin, if you're trying to get OAuth working still for account linking, I have an [example Flask project](https://github.com/voutilad/alexa-trump/blob/master/server/server.py) that shows how to navigate the oddities in how Amazon expects to broker the OAuth exchange. It uses account linking to Twitter to enable Alexa access to Twitter's APIs. (The skill logic was built for Amazon Lambda, but the OAuth part is written using Flask.)

**Comment by caseydm** [comment]
@voutilad Yes the tutorial says to use the profile scope in order to get the email address. I will give this a shot tomorrow to see if it works.
