### ISSUE TITLE
Alexa very unresponsive when playing streaming audio

### ISSUE THREAD

**Issue by jfayre** [johnwheeler/flask-ask#42]
Hello,
I'm not sure if this is related to Flask-Ask or not. When I play a stream by modifying the sample audio skill in Flask-Ask, Alexa is extremely unresponsive to commands. It often takes 3 or 4 times saying "alexa" before she will accept a voice command to pause or stop the audio. This is with an Amazon Echo. Is anyone else seeing this? 
The URL I am using for the stream is: 
https://media.grc.com/sn/sn-584.mp3

**Comment by johnwheeler** [comment]
I am not able to reproduce this issue--I don't experience delays using the new streaming audio code. This doesn't seem related to Flask-Ask, but more to the Alexa service or your particular hardware unit. I'm going to close issue for now.
