### ISSUE TITLE
Can we configure response timeout from the server? 

### ISSUE THREAD

**Issue by aayush26** [johnwheeler/flask-ask#44]
Say the server takes a longer time, can we configure so that instead of No Response reply by Echo, it will wait till our configured timeout?

**Comment by tguar** [comment]
You should be able configure the timeout in your aws console under the lambda section > configuration > advanced settings > timeout

**Comment by tguar** [comment]
@aayush26 My apologies. As far as I'm aware there is no local setting but I've been away from this for close to 3 months now.

**Comment by aayush26** [comment]
Is there any scope for such configurations later? Or is it possible to configure response timeout? 
Currently alexa waits for 10 sec to receive response from the application.

**Comment by drschlaumeier** [comment]
You could handle this timeout with python global variable and error tracking in session_ended intent? How can get session_ended reason?

**Comment by aayush26** [comment]
@drschlaumeier  Can you provide sample code snippet on how to set timeout in session_ended intent.? Different intents will be called every time from the device.

**Comment by drschlaumeier** [comment]
no, not set timeout. ... just redesign your skill. I'm using alexa since a week and programming skill since two days. I made some code to ask wolfram in german: use google translate DE-EN, ask wolfram, google translate EN-DE. This takes sometimes >10s to process. However, I save the answer (which normally comes some seconds later) into global variable. session_ended is called in case of error. 
On next start of the skill, it knows that there was an error and reads the saved answer before processing the skill.

The only question I have is how to get the error reason in session_ended.

here is some snipset:


```
from random import randint
from flask import Flask, render_template
from flask_ask import Ask, statement, question, session

app = Flask(__name__)
ask = Ask(app, "/")

#my global values
old_answer = ""
haderror = False

logging.getLogger("flask_ask").setLevel(logging.INFO)

@ask.launch
def start_wolfram():
    global old_answer
    global haderror
    if haderror == True and old_answer != "":
        welcome_msg = render_template('oldanswer').encode('utf8')
        statement(welcome_msg)
        welcome_msg = old_answer
        old_answer = ""
        haderror = False
        return statement(welcome_msg)
    else:
        welcome_msg = render_template('welcome').encode('utf8')
        return question(welcome_msg)
```

**Comment by hex4def6** [comment]
@drschlaumeier 

So how does your askill get invoked? The user says something like "Alexa, ask wolfram what the population of germany is", and then the skill times out? Does the user then have to invoke it again to get the "old" answer?

I have a similar request: I basically want to have alexa continue to listen, so the user doesn't have to say "alexa, ask MySkill to do foo1". Instead, user invokes "Myskill", and then says "foo1" or "foo2" etc.
Right now, I also have the issue where the skill times out after 10 seconds, means the user has to always preface it with "Alexa, ask Myskill...".
