### ISSUE TITLE
How to run multiple skills on flask-ask

### ISSUE THREAD

**Issue by drschlaumeier** [johnwheeler/flask-ask#45]
Hallo,
I m not clear on how to run multiple skills in flask-ask.
I have local raspi server and two different skills. I use ngrok to forward intends to my raspi server on port 5000.
Please help.

**Comment by johnwheeler** [comment]
This is out of scope of Flask-Ask, but why not try 

```
ngrok http 5001
```

to run it on a different port and get a new unique URL

**Comment by drschlaumeier** [comment]
sorry, ngrok allows only open one port at the same time....see below.
Any other suggestions?

> Tunnel session failed: Your account 'name' is limited to 1 simultaneous ngrok client session.
> Active ngrok client sessions in region 'us': (none)

**Comment by drschlaumeier** [comment]
EDIT:
Ok, I need to start ngrok with authoken and config file to open two tunnels, e.g. 5000 and 5002. BTW: max. is 4 tunnels with free account and 8 tunnels with basic account.

Is there any "FREE" reverse proxy that allows unlimited tunnels?

@johnwheeler:
I think you can close the issue. You pointed me to the right direction and its working.

Furthermore, Flask-ask is a really great starting point for alexa skill developer. So easy to use. I had my own very privat skill running in one day only. Many thanks for all you great work!

**Comment by drschlaumeier** [comment]
Edit2:
Last night I had another idea how to redesign my skills to use only one entry. I could make it like this:
Alexa, ask myskills for myapp1
Alexa, ask myskills for myapp2
Alexa, as myskills
What skill you want to use?

What you think?

**Comment by foxy82** [comment]
I don't know much about flask but you might want to look at/try and put
them on different routes?

app = Flask(__name__)
ask = Ask(app, "/")
otherAsk = Ask(app, "/other")

It might be they will need to be in different files as I'm not sure if the
@ask.launch etc are linked to the ask variable.

**Comment by shebinleo** [comment]
> app = Flask(name)
> ask = Ask(app, "/")
> otherAsk = Ask(app, "/other")

Tried this for multiple skills with different routes and I get the following error.
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    otherAsk = Ask(app, '/other')
  File ""/usr/local/lib/python3.6/site-packages/flask_ask/core.py", line 81, in __init__
    self.init_app(app, path)
  File ""/usr/local/lib/python3.6/site-packages/flask_ask/core.py", line 121, in init_app
    app.add_url_rule(self._route, view_func=self._flask_view_func, methods=['POST'])
  File ""/usr/local/lib/python3.6/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File ""/usr/local/lib/python3.6/site-packages/flask/app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: _flask_view_func

```
Is this possible with `flask-ask`?
