### ISSUE TITLE
Tutorial using Lambda Functions?

### ISSUE THREAD

**Issue by conor-f** [johnwheeler/flask-ask#46]
A tutorial where lambda functions are used instead of ngrok with an HTTPS endpoint would be very useful. Excited to start making skills for the alexa but don't want to use ngrok. I've been trying to get it to work following other tutorials but I haven't made any progress :(

**Comment by relighted** [comment]
Lambda is not covered as you have to use a deployframework like 'zappa' [1] here to deploy in AWS. Then you use the https endpoint that returns in your skill. Zappa sets up API gateway & Lambda for you.

( [1] https://github.com/Miserlou/Zappa )

**Comment by krishnakt031990** [comment]
https://medium.com/@krishnateja_182/building-serverless-microservices-with-zappa-and-flask-to-make-alexa-skills-go-live-67d639297219#.r7lod34v0
