### ISSUE TITLE
Unicode Problem

### ISSUE THREAD

**Issue by drschlaumeier** [johnwheeler/flask-ask#47]
Hallo, me again,
I have a massive unicode problem in flask-ask when encoding/decoding url's.
I'm using python google search (https://breakingcode.wordpress.com/2010/06/29/google-search-python/) to get some url from e.g. wikipedia in german. Here is some snipset:

```
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from google import search
import sys

reload(sys)
sys.setdefaultencoding('utf8')
...
mysearch =  asktext_de + " site:de.wikipedia.org"
myresult = search(mysearch, tld='de', lang='de', stop=10)
...
for url in myresult:
    print(url)
...
```

If I use this code within flask-ask it always ignores the utf8 encoding and throws me an error at "for url in myresult", error is "Unicode equal comparison failed to convert both arguments to Unicode". This is because of the german "umlaute".
If I use exactly the same code within a separate python file it runs the utf8 without problem.

Anyone has any idea what is wrong with flask-ask? Why its ignoring the utf8 ? ...and how to avoid the error of the for loop.

Many thanks!

**Comment by johnwheeler** [comment]
This cannot be a flask-ask specific problem.
