### ISSUE TITLE
new ASK JSON request and response formats are not handled (0.8.0 with zappa 0.27.0)

### ISSUE THREAD

**Issue by relighted** [johnwheeler/flask-ask#48]
My Alexa Skills are not passing certification since using zappa 0.27.0 with flask-ask as new properties to the JSON request and response formats are not handled. 
Did anyone run into this as well?

Zappa released 0.27.0 with a major simplification of the setup, doing away with many hacks, as API gateway supports ANY proxy functionality now. (see: https://blog.zappa.io/posts/unhacking-zappa-with-new-apigateway-features )

As a result, all requests are passed transparently to lambda with flask-ask and Alexa skill certification fails with the feedback: 
_"Future versions of the Alexa Skills Kit may add new properties to the JSON request and response formats, while maintaining backward compatibility for the existing properties. When we invoke the skill with additional parameters, the skill is rejecting it when we expect this to be accepted. Your code must be resilient to these types of changes.

For example, your code for de-serializing a JSON request must not break when it encounters a new, unknown property. Please see the following documentation for more information: https://developer.amazon.com/appsandservices/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference"_

Some guidance how to deal with this in code would be much appreciated.

**Comment by johnwheeler** [comment]
You might want to try to update to the latest version 0.8.1 

```
pip install flask-ask -U
```

which incorporates the work @treethought to simplify request processing. This should allow new request parameters to come through.

**Comment by relighted** [comment]
Thanks, I just completely redeployed the skill with 0.8.1 & Zappa 0.27.0. It however did not work as expected. 

The CW log contains : "'_NoneType' object is not callable_", and the skill can't be reached.

Running & calling the skill locally with ngrok in dev mode did, so I suspect an interaction between zappa & Flask-ask which is broken.

**Comment by treethought** [comment]
would you mind posting the full log message?

**Comment by relighted** [comment]
I downgraded to 0.8.0 and updated, then it worked again.

-full log of the request-

START RequestId: 8d7bafc3-acff-11e6-a977-8d84c0f4a49d Version: $LATEST
Zappa Event: {u'body': u'{"version":"1.0","session":{"new":true,"sessionId":"SessionId.fa636434-7698-4cb1-bcae-27e6b1166b6e","application":{"applicationId":"amzn1.ask.skill.2ddc8844-f60b-4af9-9319-42e0ad2e08b3"},"attributes":{},"user":{"userId":"amzn1.ask.account.XXXXXXXXXXQVFSJAJACLL7BBJBF5SJD3ZMXUT3YP5YEALJ365H5PH253YRREVNXGIJJLJ5YES2HB7AKS4CSR4AYUW3U4ITOD7BK5BLTJJ2QEVQ2TJCQM6FMWAI7KEAEOPTM2PM5IMCR3NPYNPI72QLXXLQ5OP5SPOVOUZPZUVQWPMEAB7CFMONX2COSWAVMKS3ALF4C4KSQNYKI"}},"request":{"type":"IntentRequest","requestId":"EdwRequestId.fd012642-ce3c-4b93-adba-dc4bbf00eb1c","timestamp":"2016-11-17T19:53:47Z","locale":"en-US","intent":{"name":"SurveyAnswer","slots":{"choice":{"name":"choice"}}}}}', u'resource': u'/', u'requestContext': {u'resourceId': u'65kguyrs6j', u'apiId': u'e5i2bsrrh3', u'resourcePath': u'/', u'httpMethod': u'POST', u'requestId': u'8d6b82de-acff-11e6-8989-bd002f1b124f', u'accountId': u'152837390177', u'identity': {u'apiKey': None, u'userArn': None, u'cognitoAuthenticationType': None, u'accessKey': None, u'caller': None, u'userAgent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'user': None, u'cognitoIdentityPoolId': None, u'cognitoIdentityId': None, u'cognitoAuthenticationProvider': None, u'sourceIp': u'72.21.217.155', u'accountId': None}, u'stage': u'prod'}, u'queryStringParameters': None, u'httpMethod': u'POST', u'pathParameters': None, u'headers': {u'Content-Type': u'application/json; charset=utf-8', u'Via': u'1.1 440f7503597ca64245c4258c03b08e0c.cloudfront.net (CloudFront)', u'CloudFront-Is-Desktop-Viewer': u'true', u'CloudFront-Is-SmartTV-Viewer': u'false', u'SignatureCertChainUrl': u'https://s3.amazonaws.com/echo.api/echo-api-cert-4.pem', u'CloudFront-Is-Mobile-Viewer': u'false', u'X-Forwarded-For': u'72.21.217.155, 54.240.144.10', u'CloudFront-Viewer-Country': u'US', u'X-Forwarded-Port': u'443', u'Accept': u'application/json', u'User-Agent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'Accept-Charset': u'utf-8', u'Host': u'e5i2bsrrh3.execute-api.us-east-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'4wakg-W2OEFSUYmGphOxeFTHSZ3fIVkt4eycQi5Ec88vNQJjJy5cjg==', u'CloudFront-Is-Tablet-Viewer': u'false', u'Signature': u'mJ/c8HKoyF+g9g4jD3IRDYhBKtFdqL7UBrqTdM99qj2U9es4FNH2cgA3H7TEcedjDc+58tmCTJBp0Pld3zOxKVg7E4tP1x5QjJM4y9Aw6gLwHQ13YG/Pn1dXCuhf4anO7rePKABdj6wmO3+pcfOJE9xBadYgaMTOl+W5XWk7E9NTjzoCUt3VfN/4pPWms6CHPqFpzBEygyLF+su4iaVQNRVB2Wixvrak+m7JYVFNmkMgno5Mm4nCRVCBf/DbQvwcn6/Cb8KDp85gX7d1tLhqYhhIylBWqrHXrEZbavWZntV4kV0hy8OmYijj0/z69XgQsSLklzjGGrIAhXRRlzf4kA==', u'CloudFront-Forwarded-Proto': u'https'}, u'stageVariables': None, u'path': u'/', u'isBase64Encoded': False}
[DEBUG]	2016-11-17T19:53:47.231Z	8d7bafc3-acff-11e6-a977-8d84c0f4a49d	Zappa Event: {u'body': u'{"version":"1.0","session":{"new":true,"sessionId":"SessionId.fa636434-7698-4cb1-bcae-27e6b1166b6e","application":{"applicationId":"amzn1.ask.skill.2ddc8844-f60b-4af9-9319-42e0ad2e08b3"},"attributes":{},"user":{"userId":"amzn1.ask.account.XXXXXXXXXXQVFSJAJACLL7BBJBF5SJD3ZMXUT3YP5YEALJ365H5PH253YRREVNXGIJJLJ5YES2HB7AKS4CSR4AYUW3U4ITOD7BK5BLTJJ2QEVQ2TJCQM6FMWAI7KEAEOPTM2PM5IMCR3NPYNPI72QLXXLQ5OP5SPOVOUZPZUVQWPMEAB7CFMONX2COSWAVMKS3ALF4C4KSQNYKI"}},"request":{"type":"IntentRequest","requestId":"EdwRequestId.fd012642-ce3c-4b93-adba-dc4bbf00eb1c","timestamp":"2016-11-17T19:53:47Z","locale":"en-US","intent":{"name":"SurveyAnswer","slots":{"choice":{"name":"choice"}}}}}', u'resource': u'/', u'requestContext': {u'resourceId': u'65kguyrs6j', u'apiId': u'e5i2bsrrh3', u'resourcePath': u'/', u'httpMethod': u'POST', u'requestId': u'8d6b82de-acff-11e6-8989-bd002f1b124f', u'accountId': u'152837390177', u'identity': {u'apiKey': None, u'userArn': None, u'cognitoAuthenticationType': None, u'accessKey': None, u'caller': None, u'userAgent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'user': None, u'cognitoIdentityPoolId': None, u'cognitoIdentityId': None, u'cognitoAuthenticationProvider': None, u'sourceIp': u'72.21.217.155', u'accountId': None}, u'stage': u'prod'}, u'queryStringParameters': None, u'httpMethod': u'POST', u'pathParameters': None, u'headers': {u'Content-Type': u'application/json; charset=utf-8', u'Via': u'1.1 440f7503597ca64245c4258c03b08e0c.cloudfront.net (CloudFront)', u'CloudFront-Is-Desktop-Viewer': u'true', u'CloudFront-Is-SmartTV-Viewer': u'false', u'SignatureCertChainUrl': u'https://s3.amazonaws.com/echo.api/echo-api-cert-4.pem', u'CloudFront-Is-Mobile-Viewer': u'false', u'X-Forwarded-For': u'72.21.217.155, 54.240.144.10', u'CloudFront-Viewer-Country': u'US', u'X-Forwarded-Port': u'443', u'Accept': u'application/json', u'User-Agent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'Accept-Charset': u'utf-8', u'Host': u'e5i2bsrrh3.execute-api.us-east-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'4wakg-W2OEFSUYmGphOxeFTHSZ3fIVkt4eycQi5Ec88vNQJjJy5cjg==', u'CloudFront-Is-Tablet-Viewer': u'false', u'Signature': u'mJ/c8HKoyF+g9g4jD3IRDYhBKtFdqL7UBrqTdM99qj2U9es4FNH2cgA3H7TEcedjDc+58tmCTJBp0Pld3zOxKVg7E4tP1x5QjJM4y9Aw6gLwHQ13YG/Pn1dXCuhf4anO7rePKABdj6wmO3+pcfOJE9xBadYgaMTOl+W5XWk7E9NTjzoCUt3VfN/4pPWms6CHPqFpzBEygyLF+su4iaVQNRVB2Wixvrak+m7JYVFNmkMgno5Mm4nCRVCBf/DbQvwcn6/Cb8KDp85gX7d1tLhqYhhIylBWqrHXrEZbavWZntV4kV0hy8OmYijj0/z69XgQsSLklzjGGrIAhXRRlzf4kA==', u'CloudFront-Forwarded-Proto': u'https'}, u'stageVariables': None, u'path': u'/', u'isBase64Encoded': False}
'NoneType' object is not callable
END RequestId: 8d7bafc3-acff-11e6-a977-8d84c0f4a49d
REPORT RequestId: 8d7bafc3-acff-11e6-a977-8d84c0f4a49d	Duration: 0.88 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 47 MB
