### ISSUE TITLE
Thanks! and a quick question

### ISSUE THREAD

**Issue by securisec** [johnwheeler/flask-ask#51]
Great work John! Thanks for making this! Any way you can give me a quick example of how to handle url via get and post requests? So an example would be check for something on craigslist, and then email the response....

**Comment by johnwheeler** [comment]
Hi -

I would suggest using the "requests" library for Python

https://github.com/kennethreitz/requests

**Comment by securisec** [comment]
Thanks again John. really marvelous! would you be kind enough to provide an example of how to host this on lambda? I followed directions on amazons documentation, but just cant make it work. the function_handler error i bypassed, but it doesnt want to co operate with the imports. and how do i map the flask port in lamba with the arn?

any help is greately appreciated!

**Comment by johnwheeler** [comment]
You have to use https://github.com/miserlou/zappa
