### ISSUE TITLE
Having trouble running AWS example

### ISSUE THREAD

**Issue by danielsuo** [johnwheeler/flask-ask#52]
I was referring to this [tutorial](https://developer.amazon.com/public/community/post/Tx14R0IYYGH3SKT/Flask-Ask-A-New-Python-Framework-for-Rapid-Alexa-Skills-Kit-Development) and kept getting the dreaded flask 405 method not allowed error.

This happens both locally and remotely, with and without HTTPS. Is this something you've encountered before? Thanks!

**Comment by johnwheeler** [comment]
No, unfortunately it isn't. I might be able to help if you can provide more information

**Comment by danielsuo** [comment]
Of course! We copied the code into our application [here](https://github.com/pralexa/pixie/blob/master/app.py). We're using Python 2.7.12 from Homebrew and have installed flask-ask via pip.

When we run ```python app.py```, we get a 405 error when accessing ```127.0.0.1.5000```.

![image](https://cloud.githubusercontent.com/assets/2692566/20794963/d4f7fa2e-b79c-11e6-85df-ef0b23ada63d.png)

In any case, I'm sure it's something very silly we've done, but would appreciate your help!

**Comment by johnwheeler** [comment]
Try removing sslify

**Comment by danielsuo** [comment]
Unfortunately, as I mentioned, the example doesn't work regardless of SSLify. It's effectively a no-op when debug is set to ```True```. I just took out the line and confirmed that this is still the case.

Really appreciate your rapid replies!

**Comment by danielsuo** [comment]
Also perhaps worth noting, I can properly render a ```Hello, world``` flask app, so flask, network, etc all seem fine.

**Comment by johnwheeler** [comment]
If you can prove it's Flask-Ask, I can help, but it doesn't look like it and no one else is having these problems. Please try to pinpoint the issue and reopen it. There's nothing in your code that points to Flask-Ask though.

**Comment by danielsuo** [comment]
All good; just wanted to check if this was common. Thanks again!

**Comment by johnwheeler** [comment]
I know what the problem is. There isn't one--this is to be expected. You can't visit the URL "/" with a GET request via browser. 

Flask-Ask is expecting Alexa to do a "POST". However, it's also expecting Alexa Skill JSON, so using CURL or whatever won't suffice. You need to follow the tutorial all the way through

**Comment by danielsuo** [comment]
Actually, I'm referring to POST; I'm sending POST requests from Amazon's testing service.

But as you said, let me go away and see what's going on since this isn't a problem anyone else seems to be having.

**Comment by danielsuo** [comment]
Just had a look again and indeed I was doing something boneheaded; I was using the ARN instead of HTTPS API gateway.

Thanks again for responsiveness!

**Comment by johnwheeler** [comment]
Thanks for the update
