### ISSUE TITLE
Unable to use flask_ask decorators in a flask large application directory structure with BluePrints

### ISSUE THREAD

**Issue by njohnsn** [johnwheeler/flask-ask#53]
Hi I'm trying to add alexa support using flask-ask to a larger flask application, but I can't get the decorated functions to work outside the main application module  `app/__init__.py`  file.

Here is what I had to do to get it working
```python
from flask import Flask, render_template, current_app
from config import config
from flask_ask import Ask, statement, question, session

from random import randint

ask = Ask()
ask._route = "/alexa_1_0/"

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    ask.init_app(app)

    if not app.config['SSL_DISABLE']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

#    from .alexa_1_0 import alexa as alexa_1_0_blueprint
#    app.register_blueprint(alexa_1_0_blueprint)

    return app

@ask.launch
def new_game():
    welcome_msg = render_template('welcome')
    return question(welcome_msg)


@ask.intent("YesIntent")
def next_round():
    numbers = [randint(0, 9) for _ in range(3)]
    round_msg = render_template('round', numbers=numbers)
    session.attributes['numbers'] = numbers[::-1]  # reverse
    return question(round_msg)


@ask.intent("AnswerIntent", convert={'first': int, 'second': int, 'third': int})
def answer(first, second, third):
    winning_numbers = session.attributes['numbers']
    if [first, second, third] == winning_numbers:
        msg = render_template('win')
    else:
        msg = render_template('lose')
    return statement(msg)

```
I'd like to move the route functions into a separate module ```app/alexa_1_0/views.py```, similar to when using Blueprints like this:

```python
from random import randint
from flask import Flask, render_template, current_app
from flask_ask import Ask, statement, question, session
from . import alexa

@ask.launch
def new_game():
    welcome_msg = render_template('welcome')
    return question(welcome_msg)


@ask.intent("YesIntent")
def next_round():
    numbers = [randint(0, 9) for _ in range(3)]
    round_msg = render_template('round', numbers=numbers)
    session.attributes['numbers'] = numbers[::-1]  # reverse
    return question(round_msg)


@ask.intent("AnswerIntent", convert={'first': int, 'second': int, 'third': int})
def answer(first, second, third):
    winning_numbers = session.attributes['numbers']
    if [first, second, third] == winning_numbers:
        msg = render_template('win')
    else:
        msg = render_template('lose')
    return statement(msg)

```

I created a dummy app in the the [following github repository](https://github.com/njohnsn/AlexaTest)

I'm still learning the advanced features of python, so any help would be appreciated!

_Thanks!_

**Comment by johnwheeler** [comment]
Hi - 

I take it you tried

```
app = Flask(__name__)
ask = Ask(app, '/alexa_1_0')
```

and that doesn't work?

**Comment by njohnsn** [comment]
I'm trying to follow the applicaton factory pattern using blueprints as laid out in [this O'Reilly book](https://flaskbook.com/).

If I try to move the flask_ask routes to a separate module/file I get the following traceback when I try to run the application:
```
(venv) njohnsn@njohnsn-VirtualBox:~/workspace/AlexaTest$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    app = create_app(os.getenv('ALEXA_TEST_CONFIG') or 'default')
  File "/home/njohnsn/workspace/AlexaTest/app/__init__.py", line 23, in create_app
    from .alexa_1_0 import alexa as alexa_1_0_blueprint
  File "/home/njohnsn/workspace/AlexaTest/app/alexa_1_0/__init__.py", line 5, in <module>
    from . import views
  File "/home/njohnsn/workspace/AlexaTest/app/alexa_1_0/views.py", line 6, in <module>
    @ask.launch
NameError: name 'ask' is not defined
(venv) njohnsn@njohnsn-VirtualBox:~/workspace/AlexaTest$ 
```

Is there another way to make those decorators visible in another file?

Thanks!

**Comment by johnwheeler** [comment]
Yes,

Instead of creating the `app` and `ask` variables in views.py, create them in a file called `__init__.py` that's in a package defined at the top level of your views

Here's a structure:

```
project
   foo
      __init__.py
      bar
         __init__.py
         views.py
      baz
         __init__.py
         views.py
```

in `foo/__init__.py`, you'd

```
from flask import Flask
from flask_ask import Ask

app = Flask(__name__)
ask = Ask(app, '/myendpoint')
```

then in `bar/__init__.py` and `baz/__init__.py`

you can

```
from foo import ask
```

and define routes in the respective files. Let me know if that helps.

**Comment by njohnsn** [comment]
I found the solution [here](http://flask.pocoo.org/docs/0.11/patterns/appfactories/#factories-extensions) in the flask documentation.

I moved the code out of ```/alex_1_0/``` into ```alexa.py``` and then added the following lines to file:

```python
ask = Ask()
```

Then in ```app/__init__.py``` I added the following lines:

```python
    from .alexa import ask
    ask._route = '/alexa_1_0/'
    ask.init_app(app)
```

This follows the recommendations of the flask development documentation as outlined in the link above with the exception the I have to set the route header attribute explicitly or I get an error  (Perhaps the route header should be set in an application configuration variable)?

You can close this issue.

I really appreciate your help and for authoring this very useful flask extension. 

-Neil

**Comment by njohnsn** [comment]
Thanks again!
