### ISSUE TITLE
session_ended issue

### ISSUE THREAD

**Issue by strunker** [johnwheeler/flask-ask#55]
Hello, is there anything I need to configure in utterances or in the intent schema to get this to work correctly? I have the below in my code body, and when I tell the skill to "exit" I get back an error from the echo for the skill. Which means it isnt properly handling the session ended request.

```
@ask.session_ended
def session_ended():
    print "hit session end."
    return "", 200
    # msg = render_template('exit')
    # return statement(ended)
```

I can see the below, so I know the sessioneend is being sent from the echo, but the code doesnt seem to be handling it properly. Ideally Id like to have some type of spoken message, " thanks for using me, goodbye"

```
"request": {
    "locale": "en-US", 
    "reason": "USER_INITIATED", 
    "requestId": "amzn1.echo-api.request.33c5a1d1-0036-4a7f-a5ca-e7ad268813ad", 
    "timestamp": "2016-12-04T15:46:57Z", 
    "type": "SessionEndedRequest"
```

**Comment by strunker** [comment]
Also regarding this
If I want to do debugging, you can see i dont ever seem to get that debug statement in the console view. Additionally it isnt posting back a 200 response but rather 500. 

@ask.session_ended
def session_ended():
    log.debug("calling end function for talk")
    session_ended_talk
    return "", 200


}
{}
127.0.0.1 - - [04/Dec/2016 11:22:24] "POST / HTTP/1.1" 500 -

**Comment by strunker** [comment]
This is solved by 
return statement("")

not entirely sure why returning an empty string, with a 200 post wouldnt be sufficient, but whatever.

**Comment by strunker** [comment]
It also solves the issue where if you return question("ask question") and you allow it to time out. At the end of the timeout the session end function was being called, and the audible error could once again be heard.

Fixing the closing event handler, as a byproduct, fixed this other annoyance.

**Comment by johnwheeler** [comment]
Please see issue #27 - The alexa skills kit doesn't support returning a spoken response on session_ended
