### ISSUE TITLE
Forcing a verbal response?

### ISSUE THREAD

**Issue by strunker** [johnwheeler/flask-ask#56]
is there anyway to tell the echo to "talk" outside of forcing it in the function return?

@ask.intent("SleepIntent")
def sleepy_time():
    os.system("rundll32.exe powrprof.dll,SetSuspendState 0,1,0")
    msg = render_template('sleep')
    return statement(msg) 

See the above function. what is happening here (when I call this function) is the machine is instantly falling asleep, and its never making it to the end of the function to read the string in, and therefore never triggers the return.

what i tried doing was breaking it out into two functions, so the sleep function calls the sleep talk function. I wanted to call it, have the verbal response go through the echo, then jump back to the calling function and continue on with the sleep, but this doesnt work. If I enter in debug statements, I can see that the sleep function, does call sleep talk function, but still nothing is heard prior to the sleep.

def sleepy_time_talk():
    msg = render_template('sleep')
    return statement(msg) 

@ask.intent("SleepIntent")
def sleepy_time():
    sleepy_time_talk()
    os.system("rundll32.exe powrprof.dll,SetSuspendState 0,1,0")

**Comment by treethought** [comment]
In your second example, nothing is heard because the intent function isn't returning anything. The sleepy_time_talk function returns a statement, but that occurs within its own scope and is not sent to alexa. 
Your first example seems like it might be the way to go. I don't have a flask-ask specific solution right now, but you could try calling the shutdown in a separate thread and have it time.sleep() for a few seconds so that Alexa receives the response and speaks before your machine shuts down.

**Comment by strunker** [comment]
hello,

So the code also supports shutdown, and similar to what you suggested, that is how I am handling it. I am scheduling a shutdown in 2 seconds, so that the return statement has time to actually be hit in the function.

@ask.intent("ShutDownIntent")
def shut_down():
wsh.run("shutdown /f /s /t 2")
msg = render_template('shutdown')
return statement(msg)

The problem with sleep is there isnt a nice way to do that via CLI programmatically, so whats happening in the upper example, is the function is being called for sleep. Its executing the CLI for sleep, then the machine goes to sleep before the function is done executing.

I can work around it, and I already have, by doing the below. in the below example, sleep.bat contains the sleep CLI command, the bat file also has a 3 second sleep right at the top, so it gives the function time to finish.

@ask.intent("SleepIntent")
def sleepy_time():
wsh.run("sleep.bat")
msg = render_template('sleep')
return statement(msg)

Is there really no way though similar to a print statement to tell the echo to verbally repeat text? Seems kind of silly that you can only get it to do in a function return. No way to send a post to it with text you want it to say?

**Comment by johnwheeler** [comment]
>No way to send a post to it with text you want it to say?

If I understand you correctly, that's correct. It's enforced by the Alexa Skills Kit that responses can't be initiated from user skills without prior user-initiated requests (i.e. A skill can't be built where your Echo just starts talking without the user asking it to do something).
