### ISSUE TITLE
Just getting started...

### ISSUE THREAD

**Issue by snccohen** [johnwheeler/flask-ask#57]
I am just trying to get started with this and am missing something pretty basic. I am looking for the downloads needed to do the install. PIP Install Flask-ask does nothing on my pc. I have Python 3.5.2 installed. Assistance would be greatly appreciated.

**Comment by relighted** [comment]
Presumably you are using lower caps and not how you've posted above 'pip install flask-ask'  should do it.  Do note that you should do this on a python virtualenv especially when  you also want to use zappa (pip install zappa) for deployment to AWS.
