### ISSUE TITLE
ask is running twice through process

### ISSUE THREAD

**Issue by madjack84** [johnwheeler/flask-ask#61]
Hey,

first of all many thanks to this great sdk. I already built three skills with it.

Whenever I start the script is is executed twice and therefore everytime I start threads they are also initialised twice. 
Is this a bug or a feature?
And if this is a feature, how am I able to distinguish between first and second iteration through the script?

Thanks a lot.

**Comment by johnwheeler** [comment]
this is a flask issue, actually a werkzeug issue iirc. are you using the new procedure to start an app? (i.e. flask run script)

http://flask.pocoo.org/docs/0.11/quickstart/

**Comment by madjack84** [comment]
Hey John, 
thanks for the instant response. No I think i do not use the new run script.
On the other side I found another possiblity

app.run(debug=True, use_reloader=False)

Is there any disadvantage taking this option?

**Comment by johnwheeler** [comment]
yes. i don't know what it is off hand, but you should use the new run method. from what i understand it is temporary
