### ISSUE TITLE
Zappa deployment step in details to AWS Lambda

### ISSUE THREAD

**Issue by bj32161** [johnwheeler/flask-ask#64]
Hi Jonh,
Thank you for create a good tool for us. This is really rapid way to create Alexa Skills. After I did create and testing with ngrok. Now, I would like to deploy on AWS Lambda, use Zappa. I tried to follow the instruction but not successful. 
command -> zappa init
This is result.  
Calling deploy for environment dev..
Warning! AWS Lambda may not be available in this AWS Region!
Warning! AWS API Gateway may not be available in this AWS Region!
Oh no! An error occurred! :(

I just wonder how can to get full document deployment to production base on Flask-Ask way.

Thank you
Panya

**Comment by johnwheeler** [comment]
Yes - I've received a lot of requests for this. I'll put something together within the next few days and let you know.

**Comment by bj32161** [comment]
Hi John,
Cloud you please add instruction to deploy on Heroku as well? I felt it more easier than AWS Lambda.
Thank you.
Panya

**Comment by johnwheeler** [comment]
I'm sorry. I can't do Heroku. Just Lambda.

**Comment by njohnsn** [comment]
Look at chapter 17 of [Flask Web Development](http://shop.oreilly.com/product/0636920031116.do) by Miguel Grinberg

It explains how to deploy a Flask app with Heroku.

That should get you started in the right direction.

**Comment by johnwheeler** [comment]
Here is a video tutorial I put together on how to deploy Flask-Ask skills to AWS Lambda with Zappa. Feedback appreciated

https://www.youtube.com/watch?v=mjWV4R2P4ks
