### ISSUE TITLE
QueueManager has memory consistency issues

### ISSUE THREAD

**Issue by Tyzer34** [johnwheeler/flask-ask#69]
The last few days, I have been experimenting with making a Plex Music Player for Alexa.
However, I have run into some issues regarding Python and shared memory access.
I have tried both the Queue and collections.deque methods to build a QueueManager with, as displayed in your example _samples/audio/playlist_demo_
However, with both solutions, I run into the problem that global memory access and Flask doesn’t correspond well together.
Most of the times, it is possible to access the information provided in the queue.
For example, I have written a method that allows Alexa to describe the song being played.
However, this is not always the current song being played. Sometimes, it responds with a previously played song or _None_. As these are previous values of self._current, the problem probably lies in the fact that there is no coherency between memory here.
 
Have you perhaps also experienced this issue, and if so, is there a viable solution to working with shared memory for these values? Following Python documentation, _collections.deque_ should provide thread-safe implementations for both pop* and append*. However, when I’m requesting the lengths of the current queue’s for example, they sometimes return as 0, which relates to the same problem.

**Comment by foxy82** [comment]
I've not seen this using the Queue manager can you make it happen doing specific actions?

Off topic how are you getting a URL to play  Plex music on the Alexa? I keep getting URLs that return Bad Request. Using the Plex API.

**Comment by Tyzer34** [comment]
When testing the Alexa Skill, I implemented a WhatSongIntent that returns information about the current song. When calling this intent multiple times during the same song, sometimes, it returns the name of the current song or the name of a previously played song (therefore, outdated memory access somewhere)

Mostly, the bad requests are due to not providing _https_ streams. I'm using a Plex relay server, that enables https (the one that you use when accessing Plex through plex.tv). I'm planning on writing some GitHub documentation this afternoon and putting the current code online :)

**Comment by johnwheeler** [comment]
i noticed you're using heroku, which i believe uses gunicorn. gunicorn uses a pre-fork worker model where each fork actually shares the same memory addresses, but they in fact keep separate copies of data. since the queue manager is a module level variable, you'd be getting two separate copies, which is by design with a preform worker model. this is just off the top of my head and i could be wrong about your particular use case, but it sounds like what's going on from my naive vantage point.

**Comment by Tyzer34** [comment]
@johnwheeler Thank you very much for your insight. It seems that it was caused by Gunicorn, as suggested. I changed from Gunicorn to Waitress, without any memory inconsistency problems. (although it has a slower response rate)
