### ISSUE TITLE
How to access Alexa Skill language?

### ISSUE THREAD

**Issue by jhoelzl** [johnwheeler/flask-ask#76]
Hello,

in my flask-ask pythons script, i just want to get the language of my Amazon skill (e.g. `English U.S.` or `German`). I think it can be done through the `session` variable?

I tried:
```python
session.attributes.get('language')
```

however, this does not work, because it uses my custom slot variable `language` which is not defined in my case. Any suggestions?

**Comment by treethought** [comment]
I think you should be able to access it under `request.locale`

**Comment by jhoelzl** [comment]
Thanks!
