### ISSUE TITLE
Use AMAZON.HelpIntent for current intent

### ISSUE THREAD

**Issue by jhoelzl** [johnwheeler/flask-ask#78]
Amazon suggests to use the AMAZON.HelpIntent to give the user support for the current intent / question.

How can i achieve this with this library?

When i specify my help intent with

```
@ask.intent("AMAZON.HelpIntent")
def helpme():
     return statement("How can i help you?")
```

there is no information in which intent the user currently have been.

**Comment by johnwheeler** [comment]
When you get to one of the intents that fires prior to the help intent, Save a variable on the session that keeps track of the last intent you're on. Something like

```
session.attributes['last_intent'] = 'GrindCoffeeIntent'
```

and from another

```
session.attributes['last_intent'] = 'PercolateCoffeeIntent'
```

Then from inside the `AMAZON.HelpIntent` function, grab the variable off the session to see where you're coming from

```
if session.attributes.get('last_intent') == 'GrindCoffeeIntent':
   return statement('To grind coffee...')
elif session.attributes.get('last_intent') == 'PercolateCoffeeIntent':
   return statement('To percolate coffee..')
```

The idea of conversational context is important to the Alexa Skills Kit. There's effort on this front,

An issue:

https://github.com/johnwheeler/flask-ask/issues/15

And a branch:

https://github.com/johnwheeler/flask-ask/blob/state-machine/samples/state-machine/reservation/reservation.py (see the `state` parameter that's been added to the Intent definitions)

But we have not settled on a design going forward. @treethought is working with API.AI for his library https://github.com/treethought/flask-assistant. API.AI has the notion of context, and we're going to see if we can port some of the ideas over in the future.

**Comment by jhoelzl** [comment]
Thanks @johnwheeler, that's exactly what i was searching for.

**Comment by johnwheeler** [comment]
The code looks fine to me.
