### ISSUE TITLE
For the readme:

### ISSUE THREAD

**Issue by fyngyrz** [johnwheeler/flask-ask#83]
Please specify the required Python version somewhere up near the top of the readme. Make sure you take into account anything you're importing, too -- the more non-standard stuff you import, the less likely it is the Python code will be portable across the widest range of installations.

Basically, devs need to know what they're looking at before they know if they can dig in. And when faced with a bunch of "WTF is this" imports, that becomes imperative if you don't want people to just surf away, muttering darkly about "import and word salad."

**Comment by johnwheeler** [comment]
Both Py 2 and 3 are supported. Feel free to submit a PR with version badges from shields.io

**Comment by fyngyrz** [comment]
Excellent. Say so in the readme. At the top. :)
