### ISSUE TITLE
Run audio(speech).play(stream_url) Without Ending Session

### ISSUE THREAD

**Issue by nplevitt** [johnwheeler/flask-ask#85]
Is it possible to `return audio(speech).play(stream_url)` without having the session end? It would be helpful to be able to return an audio stream and then have the skill trigger another prompt after.

I tried changing `self._response['shouldEndSession'] = True` to `false` in the audio.play definition in models.py, but that didn't do the trick.

**Comment by johnwheeler** [comment]
cam answered this one in chat.
